### ISSUE TITLE
EasyFarm Support

### ISSUE THREAD

**Issue by Mykezero** [EasyFarm/EasyFarm#130]
### Support Ticket

Use this ticket for asking questions or giving feedback about the program. You can pretty much talk about anything in this thread; use it like a mini-forum until ffevo.net is back online.

**Comment by roneeh** [comment]
What happened to it? It looks really weird right now.

**Comment by Mykezero** [comment]
Sorry for the late response; What look weird about the program? The program should look something like this: 

![EasyFarm GUI](http://i.imgur.com/Sk4JiL1.png)

**Comment by roneeh** [comment]
Oh sorry. I ment the website. x) I love your program. Nothing looks wrong about that x)

**Comment by Mykezero** [comment]
I really hope they bring back the forums...

**Comment by roneeh** [comment]
Yeah me too. You don't know if they're coming back? :)

**Comment by Mykezero** [comment]
They may not bring the forums back, but I hope they do; Here's the post where Atom0s talks about it. 
http://www.bluegartr.com/threads/122796-Ashita-v2-Windower-Alternative-Now-Live!?p=6435459&viewfull=1#post6435459

**Comment by mag100286** [comment]
Is the program broken after the most recent update on 06/24/2015?  Perhaps I need to update my FFACE or other various files contained in the EasyFarm Folder.  Can you provide a link to a working copy of EasyFarm?

**Comment by Mykezero** [comment]
Thanks for the update @mag100286. The program will probably need to be rebuilt with ffacetools integrated into it, so I'm hoping to have that done by tonight. I'll post an update here when done, and you'll be able to find it under [releases](https://github.com/EasyFarm/EasyFarm/releases).

**Comment by palladin9479** [comment]
Is there a way to keep it from spamming a JA or WS over and over again?  Currently I have it set to use Tachi: Fudo and it just keeps trying to use it regardless of current TP.  Also I have tried putting Hasso in multiple area's but no matter what it just keeps spamming it constantly.  Is this normal behavior or a result of the recent update breaking something?

**Comment by Mykezero** [comment]
The rebuilt program for the 6/24/2015 update can be found [here](https://github.com/EasyFarm/EasyFarm/releases/tag/1.10.8.17).

**Comment by Mykezero** [comment]
@palladin9479 Yeah, the update probably broke the program; Please try the updated version, and hopefully the problems don't persist ^^;

**Comment by strawbewwy** [comment]
thanks for the quick fix!

question though: it seems like the new tier 2 en spells for drk and pld it doesn't save to the file as magic. 

it doesn't autofill correctly, but even if i try to manually put it as magic, and then save the file, it will successfully save, but when i load it, it will become unknown. this sometimes become a problem if i forget to manually turn it to magic after loading, cuz i'll end up spamming in /say "enlight II" <me> all day... =x

**Comment by palladin9479** [comment]
Loaded the one you linked and while it's kinda working now, it still tries to spam the WS over and over again.  There isn't a place to put in how much TP to WS at so likely reading some value incorrectly.  That might be an idea to add in the future, a minimum TP value or something.

**Comment by Mykezero** [comment]
A lot of the ability options are hidden under context menus; I should really find a better way for displaying those options...

Anyway, you can adjust the weaponskill's minimum TP by
1. Right clicking on the weaponskill
2. Clicking the "General Options" right click menu option
3. Setting the TP Cost value to 1000

The screen should look like this. 
 
![TP Settings](http://i.imgur.com/PUX52s4.png)

**Comment by mag100286** [comment]
Do you have a link to a repacked Retro EasyFarm program?  I really prefer the old EasyFarm over the new one.  Ever since this update recently, the bot will not target enemies, it just runs past everything.  Any help is greatly appreciated.  Thanks.

**Comment by Mykezero** [comment]
@mag100286 I've added the retro version to the current release now.

**Comment by palladin9479** [comment]
Oh wow thanks, that fixed my Ws issue.  Next up is incorrect index's for Haste Samba lol.  I set haste samba and it just tries to spam it, I'm assuming that's because the index was changed or what not.  How would i go about determining the correct value for that?  And is there a way to say to only use Haste Samba if the status effect wore off?

Sorry for all the questions but haven't seen any guides or documentation of EasyFarm and I'm kind of a noob to it.

**Comment by novowels** [comment]
Just downloaded.  Got it started up, but it keeps crashing whenever I select my character process.  Any suggestions?

**Comment by HOPIDev** [comment]
Hi folks !
Does anyone know if there are some compatibiliity issues with W10 ?
It seems it does not work anymore, whatever i try, since i upgraded my system.
Do you have any clues or suggestions ?
Thanks in advance !
Regards

**Comment by Mykezero** [comment]
@HOPIDev  Sorry for the late response. Another person once reported there were problems with EF on Windows 10, but I don't know if it was ever resolved.

**Comment by Mykezero** [comment]
@novowels Make sure you have the [requirements](https://github.com/EasyFarm/EasyFarm#requirements) updated and installed. **Important** : Make sure you install the 32 bit version of the visual studio C++ redistributable even if your operating system is 64 bit; fface depends on the 32 bit version. 

Also, are you running the program as an administrator? This can be done by right clicking the application, and selecting "Run as Administrator". 

Has there been an update recently? That could be causing the program to crash.

**Comment by HOPIDev** [comment]
Hi Myke !
I finally found a way to make EF work again.
I installed a VM under W7 from where i build the solution through VS2013.
Then,on W10, i run the build with W7 compatibility parameter set.
I still have some weirds random crashes now and then but at least it is usable again.

Regards,
and sorry about my poor english ^^;

**Comment by pairak** [comment]
I just downgraded to Win 7 and EF still crash the moment I attach my character. The retro seems to work, but it refuses to weaponskill so the normal one would be nice :)

**Comment by zerodivine** [comment]
Hello,
Whenever I am switching on the Battles tab between Start, Pull, Battle, etc.  The pulldown menu goes from job ability or weapon skill back to unknown.  This cause the app to spam the ability or spell in say and was wondering if there is a way to prevent this?

**Comment by Mykezero** [comment]
Yeah, I just saw that behavior yesterday but I wasn't sure what caused it. I'll look into see what's causing it.

**Comment by Mykezero** [comment]
@pairak  I'm not sure if any of the current changes have fixed it, but this version might fix the problem: 

https://ci.appveyor.com/project/Mykezero/easyfarm/build/1.0.18/artifacts

**Comment by rmforr2** [comment]
I love your program and use it often.  I also use another tool for the follow function only.  Any chance you've thought about adding some logic to /follow a selected character between selectable distances?  I've started to read up about lua programming hoping I could build a simple /follow program, but no such luck yet.  Chapter one is way over my head.  Your program feels quirky if I just /follow another toon without stopping a certain distance away.  Keep up the great work.  Downloading the latest build now.

**Comment by Mykezero** [comment]
@rmforr2 Terrific idea, and I'll try to add it in as soon as possible!

For learning Lua, I highly recommend the Windower team's [Lua Guide for Programmers](http://legacy.windower.net/topic/21924-lua-guide-for-programmers) article with emphasis on the tutorial section where it talks about assignment, loops, tables and functions

Also check out the open source lua projects provided FFEVO and Windower teams. 
* http://delvl.ffevo.net/public/projects
* https://github.com/Windower/Lua

I've written a few addons in Lua that may be a bit easier to understand since I'm a beginner, and have stayed away from some of the more complicated things. 

Windower Addons
* [HealthTriggerScript](https://github.com/Mykezero/Health-Trigger-Script) - triggers a script based on target's health. (simpler)
* [BindNChat](https://github.com/Mykezero/BindNChat) - example addon that disables / re-enables keybinds. (more complex)

Ashita Addons
* [RapidFire](https://github.com/Mykezero/RapidFire) - autofires ranged weapons. (simpler)
* [RecipeRetriever](https://github.com/Mykezero/RecipeRetriever) - queries crafting recipes from from a file. (more complex)

Good luck and best wishes with Lua programming!

**Comment by Mykezero** [comment]
Updated to fix problems with pausing the program.

**Comment by Mykezero** [comment]
@rmforr2 Following has been added.

**Comment by Elvtin** [comment]
Hello!
I was trying to setup Easyfarm and am having trouble getting the Weaponskills to work.

Aside from this it has been working pretty well.

Any suggestions on what have set wrong?
Here is what the setup looks like. 
![easyfarm](https://cloud.githubusercontent.com/assets/15043686/10385514/f17c0f2a-6e17-11e5-8a52-9815b3112b83.JPG)

**Comment by Mykezero** [comment]
@Elvtin It looks like the index for Dancing Edge is wrong, and the value should be 791. Also, you don't have to specify a mob's name in the enemy's area. Once the index has the correct value, the program should weaponskills all mobs (unless you want to specifically use that weaponskill only on Giant Spiders). 

Also, to pull index values from the resource files you can click the Auto-Fill button, and the Index should be pulled in automatically. Was 23 the value generated by autofill?

**Comment by Elvtin** [comment]
@Mykezero   Thanks for the info.  I believe the autofill put in either 600 or 900.  It seemed to do this with both Dancing Edge and Viper Bite. 
I'll change that around and see what happens.

Another question. 
Is it possible under the Pull section to have it do a regular ranged attack to pull the mob?

**Comment by Mykezero** [comment]
@Elvtin Yeah, the weaponskill index values in the resource files might be out of date. Viper Bite's index should be 785. I'll have to check the resource files to see if they're up to date. You can do regular ranged attacks on pull by entering Ranged for the action's name.

**Comment by Elvtin** [comment]
I've having an issue with the latest version, I saw you updated it so I grabbed it.
I'm trying to farm Sabertooth Tigers in Carpenters Landing.

Looking at the log while the bot is running, it's showing that it's targeting the mob but then just continues running past it and ignores the mob. No actions are taken against the mob.

The tigers are sometimes up on the side of the hills so I adjusted the Height Threshold to 10 but that doesn't appear to have made a difference.

I've also noticed that when the bot is set for a ranged attack under Pull it doesn't wait long enough for it to go off. It starts the action then moves interrupting the ranged attack. 

Let me know if there is anything more specific I can provide for troubleshooting.

**Comment by Mykezero** [comment]
@Elvtin Thanks for the heads up, and I'll see what's going on in carpenter's landing along with the ranged attack problems. Are you using a long or short delay bow?

**Comment by Elvtin** [comment]
Using the Power Crossbow.  Has a delay of 288.

**Comment by rmforr2** [comment]
@Mykezero I was playing around with this today and noticed the default index for all weapon skills is 900 when using auto-fill.  Also, the auto-fill could not find the references for Addle II or Distract III.  Where would one get the "updated" index values?  I don't mind doing some leg work.

**Comment by rmforr2** [comment]
@Mykezero I opened the resource file for abils and noticed the index="900" on all weaponskills.  I'm sure that was not always like that.  It looks like it is only on the weaponskills.  The 2-hour abilities have a index="0" which doesn't seem right.  I could try to research and edit it if I had some guidance.

**Comment by Mykezero** [comment]
@rmforr2 Sounds likes there's a conflict between the travel and weaponskill state; I'll add the problem to the issue tracker.

**Comment by zaxtiss** [comment]
You can find the id of one hours and weapon skills in the windower files

**Comment by Tanag** [comment]
Glad I found this again with the forums gone.  Thanks for continuing development!

How safe is this app these days?  I haven't touched it since the massive ban waves a few months back, but those seemed mostly related to speed hacking.  I'm sure afk farming is out, but how about everything else?  I'm mostly interested in idle but non afk CP farming or seeing if I can get it to work well in Dynamis.

**Comment by Mykezero** [comment]
@Tanag I haven't played on the live server in ages so I don't know what the chances of being banned for using it is. Hopefully someone will have an answer as to how often and how long they've been using the program. 

I don't recommend afk farming since the AI isn't there yet to properly handle other players "playing tricks" on the AI controlled player.

**Comment by Tanag** [comment]
Thanks for the reply, hopefully someone else has some insight.

Yeah I'll never use it afk.  Even back in the day I wouldn't fully afk when using it.  Too paranoid haha.

**Comment by focusbob** [comment]
I'm having a problem where the bot stays too close to the mob no matter what I set the distance at and says "Cannot see <mob name>". It still hits the mob but I cant ws as frequently as I would like (once i hit 1000 tp) On my second character which I'm running at the same time, it wont ws at all ever. Not sure whats causing this because I never had this problem before. I was using the program last year around this time so it was a different version. I quit the game and came back recently.

**Comment by Mykezero** [comment]
@focusbob I've updated EF to fix a problem where the program would try to run its waypoint path in battle which may have been causing that problem.

**Comment by Mykezero** [comment]
I've added [Tutorials](https://github.com/EasyFarm/EasyFarm/blob/master/Documentation/index.md) on creating basic actions / spells but it's in rough shape. I'll try to expand on the program's other uses  besides farming like leveling enhancing, healing and divine magic skills.

**Comment by zaxtiss** [comment]
Would it be possible to make the program run 1  set of way points for certain parts of the game day? Like in dyna could make it run thro  diff parts of the zone depending on the proc time?

**Comment by Mykezero** [comment]
@zaxtiss Dynamis / Abyssea support is something I'd like to integrate into the program so this does sound like a good feature. Are there any other features / improvements to make using the program in dynamis more friendly?

**Comment by rmforr2** [comment]
It's funny, I was just thinking about EasyFarm and Dynamis on my way to work.  Is it possible to trigger a WS upon a successful JA proc?

**Comment by Mykezero** [comment]
@rmforr2 It's possible, but the feature isn't in the program yet ^^; I'll add it to enhancements.

**Comment by Nasteff** [comment]
Can you please fix geomancer spells.  just spams them over and over since the status effect is not the same...example indi-refresh and indi-haste.  i use "Max use" function to limit this but i still dont need it cast every fight.

**Comment by Mykezero** [comment]
@Nasteff How about I add a recast field to make these spells cast only once every 180 seconds? This way you can set how long to wait before the next cast of indi-haste should occur?

**Comment by Nasteff** [comment]
that would work as well ^^

**Comment by focusbob** [comment]
Would something like that be able to work for cor rolls also? I try to set up rolls and it just keeps trying to use the ability over and over even though theres 6 minutes or so on it.

**Comment by focusbob** [comment]
Not sure if this is a problem with my pc or program, but it was working great for a couple weeks now and all of a sudden it doesnt want to use ja's or ws's anymore. Tried removing and reinstalling from my pc but to no avail. Tried logging my char, restarting easyfarm but nothing is working.

**Comment by LoireMar** [comment]
@Mykezero Just recently picked up using this again, I am not sure if its due to the most recent update or this was a case before but when selecting the weapon skill rudra's strom the program constantly spams it even without the character having enough TP to do so. Also doesn't recognize evisceration as a weaponskill.

**Comment by focusbob** [comment]
Not sure if this is working for anyone else after the November update, but everything besides pathing is working fine for me. I set a route in Woh Gates and it doesnt  follow it, but I set one in Windurst and it followed it no problems.

**Comment by Mykezero** [comment]
@focusbob Within the same zone try a different farming area; There's a chance the program is trying to attack an invisible or inactive mob.

**Comment by Mykezero** [comment]
Also FFXI is free until the 23rd so I get to level my dragoon <3!
http://www.playonline.com/ff11us/vanaproj/wcb/index.html
So you private server users can come and have fun!

**Comment by focusbob** [comment]
I switched zones and its working flawlessly. Other camps in Woh it seems people are using this or another similar program so I didnt want to be an intruder. Stinks because Woh is a good gil making spot but oh well lol. Anyways, any status on possibly throwing in a recast field so I can Haste 2 myself instead of relying on unreliable trusts for it?

**Comment by Mykezero** [comment]
@focusbob Nah, I haven't started working on adding ability recasts but it's in the gameplan of upcoming features to implement.

**Comment by Mykezero** [comment]
Alright ability recasts have been implemented but not really tested. To access this new feature right click on an ability and select "General Options". The new recast option is at the bottom and action recast are specified in seconds. Pausing and restarting the program will cause all recasts to be reset in case spells or actions stop working.

**Comment by Mykezero** [comment]
@focusbob Wait, Haste II should work and should be recasted when it wears off. Is this a problem for you? Sorry for not catching on to that sooner if this works. This is how I would setup the program for Haste II: 

![](https://raw.githubusercontent.com/EasyFarm/EasyFarm/master/Documentation/images/issue130/haste-ii-settings.png)

**Comment by miller65336** [comment]
Having an issue under the "Pull" menu. Any magical spell I use to try to pull gets repeatedly interrupted. Even fast casting blue Mage spell glutinous dart. Is there a way to make the character stop running and then cast the spell to avoid interrupts?

**Comment by Mykezero** [comment]
@miller65336 The program should automatically stop running when attempting to cast a spell; I'll see what's causing the problem.

**Comment by focusbob** [comment]
Well, I'm on BLU and I'm trying to keep Erratic Flutter up, which is basically BLU's Haste 2, as well as Nature's Meditation. The problem is after every fight it tries to recast them both. Big problem is that I farm on VT mobs and when I have aggro or a link, not whackin a mob and casting a spell can mean the difference between my trust gettin off a cure 6 or me hp'ing.

**Comment by focusbob** [comment]
I should've specified that I was using Flutter, not Haste 2.

**Comment by miller65336** [comment]
Is there some kind of auto kill function for the application?  The reason I ask is because it usually only runs for 5-6 hours before I just end up dying for no apprent reason. I'll look back at the log and just see where a mob was beating on me until I die and eventually home point with no actions taken by my character.

**Comment by miller65336** [comment]
I should add that I'm not really complaining. This works exceptionally well I'm just trying to see if I overlooked something.

**Comment by Mykezero** [comment]
@miller65336 Yeah, I didn't really design the program to run for long durations; The AI runs on a single thread so if for some reason that thread goes down the character will no longer be controlled. It's possible to run the program for long durations but I can't assure its reliability.

**Comment by miller65336** [comment]
Is there a setting on my end I can change?

**Comment by Mykezero** [comment]
@miller65336 There's no setting that can be changed, but I could look into making the program more reliable for longer durations if you'd like?

**Comment by miller65336** [comment]
That would be great!!

**Comment by miller65336** [comment]
Having an issue with the new version where it won't fire off any weapon skills anymore. The strange this is earlier today it was working fine (with the new version), but when I loaded it up this evening it won't use any weapon skills even though I loaded my working saved settings. I even tried re loading and creating a new setting and it still won't work.

**Comment by Mykezero** [comment]
I would re-download the program and recreate those settings to see if that fixes the problem. Otherwise it's probably a bug with the software. Also, what is the weaponskill and weaponskill configuration you are using?

**Comment by miller65336** [comment]
Looks like today's update broke the program. Boo to you SE!

**Comment by miller65336** [comment]
To elaborate a little more:  the biggest problem right now is the bot won't target any mobs. After a couple clicks on the start button in the menu my character will start running my recorded route but it won't target/attack any mobs.

**Comment by Mykezero** [comment]
Thanks for the updates. It looks like lolwutt and at0mos have added some fixes to the fface.dll file. I'll be working on repackaging the program now.

**Comment by Mykezero** [comment]
Alright, the program has been repackaged and is available under releases.

**Comment by focusbob** [comment]
Downloaded the new package and my char is still just standing there like a dunce.

**Comment by rolares** [comment]
I'm honestly sorry to ask such a bad question here, but how do I execute this; is it a plugin/add-on? I'm very likely completely missing the most basic fundamental step 1 here, lol.

**Comment by Elvtin** [comment]
It's just an exe that you run, which opens a window.  it's a program outside the game.

**Comment by rolares** [comment]
I'm not seeing the executable, which folder is it in? Thanks for the response

**Comment by Elvtin** [comment]
Should have a folder with around 24 files and 1 folder.  It's Easyfarm.exe

**Comment by rolares** [comment]
You know what, I download the EasyFarm master-zip which only had 14 files and no executable in the index; just a heads up for anyone who isn't normally on github like me, to look for the latest full release and not just the zip of changes.

Thanks for the fast reponse, and sorry about that.

**Comment by Monosss** [comment]
I'm having problems targetting mobs since the newest update. Not sure if it's the FFace.dll file or not.

**Comment by rolares** [comment]
Has anyone had issues with it not opening on Windows 10 (or is it a known issue)? I've tried running it under a number of previous compatibility modes and of course as administrator. 

Issue is that it hangs before the program even opens up the UI (i.e. hour-glassing)

**Comment by frenchies5** [comment]
You guys. Take 5 mins and read a few comments back. With the new update,
only a few features are working. Monster targeting is NOT working. Give the
developer some time and hopefully he'll have it up soon.

**Comment by rolares** [comment]
Sorry. I didn't see anything pertaining to hanging for the current server update (just possibly packet read errors i.e. mob targeting, assist, etc.). I posted because of problems even prior to that. That's why I wanted to try others here in the support thread. 


>You guys. Take 5 mins and read a few comments back. With the new update,
only a few features are working. Monster targeting is NOT working. Give the
developer some time and hopefully he'll have it up soon.

**Comment by Mykezero** [comment]
It looks like too many things are broken even with the new version of fface.dll. I'll have to wait until a  new version is release before EF will work again.

**Comment by focusbob** [comment]
Guess the fface still hasnt been updated so no chance for a xmas present this year?

**Comment by Mykezero** [comment]
@focusbob  Yeah, I'm still waiting for a response as to whether ClaimID and IsClaimed is broken for FFACE. 

@SG1234567 was kind enough to contribute a fix for the IsRendered problem so the program should no longer attack unspawned skeletons, bats or elemental #164. 

I'll continue to work on stabilizing the program and to make it work better with the new library.

**Comment by Mykezero** [comment]
I've fixed a bug where the program would attempt to cast abilities when the recast wasn't up along with a few other things.

**Comment by rmforr2** [comment]
@Mikezero how difficult would it be to use a macro button (erg. Ctrl+1) from the battle menu?

**Comment by Snoopyslr** [comment]
That would be REALLY helpful.  I don't use spellcast or anything, so I'm stuck WSing in the gear I'm wearing.

**Comment by Mykezero** [comment]
We're talking about using the macro system instead to launch moves?

**Comment by rmforr2** [comment]
Yeah, for instance, I want to fire off a SC and have a /equip in the macro

**Comment by Mykezero** [comment]
Would using the new equip sets commands work? If you had weaponskill gear in equipset 1, we could send /equip set 1 before a weaponskill executes?

**Comment by rmforr2** [comment]
personally, I was thinking of using it on Beastmaster.  My macro would Blockhead, wait the appropriate time and then Tail Blow.  That way I can SC consistently

**Comment by Mykezero** [comment]
My main concern is how would the program know which whether an action in the macro could be casted? It's definitely an interesting idea; I'll think about it some more and see what I come up with.

**Comment by SG1234567** [comment]
After testing in different areas I have found 2 things: 

1.  I have had some issues with areas that contain a "???". I cannot ignore this and it makes my character unable to farm near them (will forever try to attack it).
2.  I found a place in "outer R.." to fight Decent challenge fomors, but they seem to be considered NPCs and not Mobs so it will never engage them.

**Comment by Mykezero** [comment]
@SG1234567 I think I've fixed the first problem of attacking ??? and field manuals. I'll have to look into the second problem though ^^;

**Comment by Monosss** [comment]
Are we still waiting on the FFace update, or should the tool be working now?

**Comment by Mykezero** [comment]
@Monosss The program should be pretty reliable now with the new api and should be working.

**Comment by Mykezero** [comment]
I've created a forum post on [EliteMMO](http://www.elitemmonetwork.com/forums/viewtopic.php?f=10&t=394&sid=8152260e9de28e6e0a8319cae7701bd0
) for EasyFarm for asking questions or making suggestions as well.

**Comment by focusbob** [comment]
I havent really been playin ffxi at all so I haven't downloaded any easyfarm updates until today. Now each time I go to select character, it has everything thats open on my pc (web browser, antivirus, easyfarm, ffxi character) as thing I can select to set as my character. So when I choose my ffxi character, i get the message "Object reference not set to an instance of an object" and EF crashes. Is this something on my end or the programs end?

**Comment by Monosss** [comment]
Check the instructions listed under "Notice" I got caught by the same issue.

**Comment by Mykezero** [comment]
Locking this issue since it's getting kind of long; a new support issue has been opened here:  #192
