### ISSUE TITLE
Program Won't Target or Engage Mobs

### ISSUE THREAD

**Issue by mag100286** [EasyFarm/EasyFarm#131]
When I attempt to add a target to the program, the target will not add.  If I add the target manually by typing the target's name, it will add.  But, when the program is started, the character will run to designated nodes like normal.  The program will not target the added targets, or engage the targets. 

I just reinstalled Windows 7 x64, installed necessary software (that i'm aware of), but I cannot get this program to work properly.  Any suggestions would be greatly appreciated. 

Thanks.

**Comment by Mykezero** [comment]
Hopefully one of the new versions of the program will work for you. I'll close this issue temporarily, but if you're still having problems we can still try to solve them.
