### ISSUE TITLE
Unable to see - reoccurring error (taru discrimination!)

### ISSUE THREAD

**Issue by novio** [EasyFarm/EasyFarm#132]
Unfortunately I'm receiving the 'unable to see' target error quite frequently. 

I've adjusted the fighting distance to the enemy and detection of enemies but to no avail. More often than not as a tarutaru it will partially stand 'on' or 'inside' the mob. Somehow, adjusting the height detection alleviated the issue a slight amount though it does still occur.
In contrast my hume and elvaan do not experience this issue while having the exact same settings.

Any help with this would be greatly appreciated!

Thanks for your time :)

**Comment by Mykezero** [comment]
This is one of the core issues I want to resolve. Ideally, the program should automatically adjust its distance based on "Unable to see" and "Out of range" messages. I'll see what I can do about adding this feature which should help out the tarutaru.

**Comment by novio** [comment]
You're awesome! Thank you Mykezero

**Comment by Mykezero** [comment]
@novio This was added in one of the new updates to EasyFarm :wink:
