### ISSUE TITLE
Weapon Skill

### ISSUE THREAD

**Issue by jcv-** [EasyFarm/EasyFarm#138]
Is there a way to make it so that it weapon skills at a certain %? It seems to only weapon skill on pulls.

**Comment by Mykezero** [comment]
Do you mean TP percent for weaponskills or health percent for mobs?

To weaponskill at a certain TP percent, you can follow the instructions in Issue #139. 

To weaponskill based on the target's current health percentage, you'll want to 

1. Right-click on the weaponskill, and select Enemy Options. 
2. Adjust the health slider at the bottom of the enemies section to the desired health. 

![a](http://i.imgur.com/31mzWwz.png)

Hopefully this solves your problem, and sorry for the late response ^^;
