### ISSUE TITLE
Zoning Problems

### ISSUE THREAD

**Issue by Mykezero** [EasyFarm/EasyFarm#14]
# Current problems after changing zones

These are the current problems when the player zones after starting the program. 
- [ ] PlayOnline crashes
- [x] Weaponskills fail to trigger
- [x] Program stops working

This is a top-priority bug that effects the program's usability
# Temporary solutions
- Use Ashita which seems to be more stable. 
- Restart the program when each zone to restore functionality.

**Comment by Mykezero** [comment]
This bug is still not resolved and seems to affect users that use Windower. The cause is still unknown. It happens when the player zones after EasyFarm has run (crashes occurs with EF running or was running and has been closed)

**Comment by Mykezero** [comment]
Zoning causes issues with triggering weaponskills.

**Comment by Mykezero** [comment]
On my machine, zoning stops the program from functioning properly. So, a program restart would be best.

**Comment by KenshiDRK** [comment]
Could the zoning crash in windower be caused by the way Easyfarm handles targets? after running the program easyfarm will keep the target even after dead until you select another target, this will persist even after pausing or closing the program and between zones. For example, if you are using the tparty addon of windower it will keep the hp% of the last mob you have targeted even if you stop targetting it, when it should dissapear.

**Comment by Mykezero** [comment]
This might be a side effect of FFACE's SetTargetNPC function. It overwrites the player's current target in memory and even when the mob is dead, our target is still set to that target (in this case to a dead mob). 

The initial versions of EasyFarm never used this function but the zoning problem still existed so I don't think it would cause the zoning problem. I'll do some testing just in case though, especially if it has the potential to solve this problem. Thanks for the help ^^

**Comment by Mykezero** [comment]
New code may fix this problem. /pray for it to work!

**Comment by Mykezero** [comment]
I've checked off the two problems I've tested and work reliably.

**Comment by Mykezero** [comment]
Still seems to occur after teleporting on death in Windower 4.

**Comment by thicksz** [comment]
i have to keep hitting start each time i Zone anything about that ? Ashita here

**Comment by Mykezero** [comment]
That functionality was removed in issue #159. I could reintroduce it into the program if you'd like? I would probably make it optional by adding a checkbox somewhere to enable / disable the feature. I'll need to fix that running after zoning problem, but it can be done!

**Comment by thicksz** [comment]
That would be awesome  was working  fine for me long ago .. what's nice
still works/stays running  when in abby hitting  the Flux as long as the
one that's being follow dose Flux warp first love it .. .wish there was way
to make bot stay 20y from so if u move back they will move back and keep
the 20 y ..

**Comment by thicksz** [comment]
ok i just downloaded ver 1-0-49 tested from new ver to 49 ... and 49 is workking pimp for me as of following when i zone LOVE it ... windows 10/ashita .... but do u think im missing anything cuz of all the othere updates afer 1-0-49 that i may need ? but all looks to be working very nice.. if u do add it back in in last ver update let me know plz .. but 4 now ill run 1-0-49...

**Comment by thicksz** [comment]
blahh only the following is working on ver 1-0-49 not anyhthing else hmmm

**Comment by thicksz** [comment]
ok cool well if u add it back would be awesome it has aways worked well for me when i had it be4 and ver49 is running Nice right now the foloow after zoning ...

**Comment by Mykezero** [comment]
Alright, I've pushed version 1.0.82 which should not pause the program after zoning. 
In addition, I've added logic that binds a given recorded route to a specific zone.

**Comment by thicksz** [comment]
Won't awesome it's working perfectly for me thank u very much told few my
friends they love it

**Comment by Mykezero** [comment]
Closing this ticket since we are no longer using FFACE and this could have been an FFACE problem.
