### ISSUE TITLE
Autofill failed to find...

### ISSUE THREAD

**Issue by ConanOb** [EasyFarm/EasyFarm#145]
I keep getting this message: "Auto-fill failed to find (insert spell here) in resources. The spells in question are Endark, Endark II and Tier 6 spells, I havent gotten that message for anything else yet. I've tried manually inputting the index, mp cost, recast but it still wont use the spells in question. I found Endark in the resource folder but couldnt find any of the other spells, is there an updated resource folder im missing? Thanks in advance!

**Comment by Mykezero** [comment]
Hi @ConanOb, 

I've updated the tutorial section with a guide for finding index values.
* [Tutorials](https://github.com/EasyFarm/EasyFarm/blob/master/Documentation/index.md)
* [Finding index values](https://github.com/EasyFarm/EasyFarm/blob/master/Documentation/action-indexes.md)

But here's the short answer (hopefully they work!) ^^; 
> Now, with the highlighted values we found, we can build the following list:

> Index | SpellName
---|---
856 | endark_ii
855 | enlight_ii
854 | water_vi
853 | thunder_vi
852 | stone_vi
851 | aero_vi
850 | blizzard_vi
849 | fire_vi

**Comment by ConanOb** [comment]
It worked like a charm! Thank you so much for all your help and this great program!

**Comment by ConanOb** [comment]
I just noticed that its not waiting for Endark II to wear off before casting it again. I tried using the player submenu following the instructions in the tutorial but when I check the effect box it doesn't cast Endark at all and when its left unchecked it casts every time the recast timer is up.

**Comment by Mykezero** [comment]
Give these settings a shot; Endark II should only be casted when the endark status effect wears. 

I've put the effect in the end list so that it will be casted anytime it wears off (I guess I should really rename end list to buffing list....)

![](https://github.com/EasyFarm/EasyFarm/blob/master/Documentation/images/issue145/endark-settings.png?raw=true)

**Comment by Mykezero** [comment]
Whoops, looks like end list really only triggers when the target is invalid (dead or no valid mob near by). The battle list should work, but set the distance to 50 so that it will trigger no matter how far the current target is away from your character.

**Comment by ConanOb** [comment]
That seems to have done the trick, I had the box checked and typed "Endark II" in the player submenu box instead of just "Endark". Thanks again for all your help!
