### ISSUE TITLE
Assist

### ISSUE THREAD

**Issue by Nasteff** [EasyFarm/EasyFarm#149]
Would it be possible to add an assist field?  so when running on multiple chars they will stay together and not run off or attack 2 seperate mobs

**Comment by Mykezero** [comment]
Give these settings a shot and tell me what you think: 
![](http://i.imgur.com/bZbYbLn.png)
The followers will then follow the leader and will only attack creatures the leader attacks. Now, the leader could either be you controlling your character or another instance of this program with normal settings.
