### ISSUE TITLE
Not engaging mobs or performing any abilities

### ISSUE THREAD

**Issue by Alyssa-momochan** [EasyFarm/EasyFarm#152]
Hello!

I'm using the latest FFACE.dll and tried 5 versions of EF (current version then tried a few versions back).

Since the Dec. update sadly EF hasn't been working for me. It will run a path but not engage any mobs at all. If I manually engage an enemy it won't do any of the abilities. 

I have seen others post about FFACE being the problem but I don't know if this is right. I'm using another program called MyProject that uses FFACE right now and it can engage mobs and do abilities. I wish I knew what to say to help pinpoint this

I prefer EF since it's better designed and it is not a memory hog. I'm simply 'making do' for now til EF is working again :)

I would like to donate too but I don't see the option anywhere. I'm not sure if you want to make it one but in any case I just want to say thank you for making and updating EF since there really is seriously nothing else that comes close to it lol

Tyvm <3

**Comment by Mykezero** [comment]
@Alyssa-momochan Well good news, I just published the version that use the mmoelite api so mostly everything should be working with that version (1.0.56). I'll try to work out the kinks with the FFACE version but I think the ClaimID is still broken in some cases (Tested in East Ronfaure (S) on carrion worms and half have a claim id when unclaimed...). There's probably still a few bugs to fix but at least it should target mobs ^^;

**Comment by SG1234567** [comment]
I downloaded 1.0.56 and continue to get "object reference not set to an instance of an object" when i select my character. Is there something else that i need to configure to use this release?

**Comment by Mykezero** [comment]
Does this happen after opening the program or when the start button is pressed?

**Comment by SG1234567** [comment]
As soon as I select my character from the list.

**Comment by SG1234567** [comment]
![image](https://cloud.githubusercontent.com/assets/16248482/11831514/bb35c358-a363-11e5-9c88-093be6e1a7c2.png)

I removed my characters name for reasons :)

**Comment by frenchies5** [comment]
I have the same issue.

**Comment by SG1234567** [comment]
I keep getting stuck on this:
EliteAPI = new EliteAPI(pid);

After a shit ton of research and testing, I found that EliteAPI requires specific Windows redistribution packages that I presume FFace does not need. If you go to their site you can download the "EliteMMO Systemcheck". Here is what mine looked like:
![image](https://cloud.githubusercontent.com/assets/16248482/11835033/4f288aba-a386-11e5-8680-febcff2ee941.png)

After going to Microsoft.com and downloading the files that it said I was missing I got it working.

**Comment by Mykezero** [comment]
Thanks for going the extra mile and finding a solution to the problem: It didn't occur to me that it would require a different set of dependencies >.<. I'll have to update the documentation to include the new requirements for the program.
