### ISSUE TITLE
Log is not working

### ISSUE THREAD

**Issue by Mykezero** [EasyFarm/EasyFarm#155]
The log tab is no longer functioning and would be helpful in determining what target the program is trying to attack.

**Comment by SG1234567** [comment]
Looks like in your last release you got this working again!
Here is something that is poping up right after it starts:
![image](https://cloud.githubusercontent.com/assets/16248482/11865793/45e4aa62-a45b-11e5-8758-bb733a771cb3.png)

**Comment by Mykezero** [comment]
I just tried it on the computer at work and it's working as well. Hmmm.... maybe my laptop is missing something. Still have to fix that argument / parameter problem though ^^;

**Comment by Mykezero** [comment]
Log has been fixed; now using NLog for logging instead of semantic logging block.
