### ISSUE TITLE
Memory Leak in 1.0.58

### ISSUE THREAD

**Issue by SG1234567** [EasyFarm/EasyFarm#156]
There is a memory leak somewhere. It takes a few hours of running to get to this size:
![image](https://cloud.githubusercontent.com/assets/16248482/11860735/c4cbbf52-a42c-11e5-8b80-c43920c57ac8.png)

It starts at around ~37.5mb, and will eventually throw an unhelpful error and close.

**Comment by Mykezero** [comment]
Indeed, the memory should never be that high; thanks for the report!

**Comment by SG1234567** [comment]
I don't know the exact way to find what is not being disposed. I let it run while I was at work, here is the spot it finally got stuck on. If I were to make a guess, it would be the api object. I think it might be made every call and kept in memory. It looks like you made a copy of it for each class that you create 
this.api = api;

I would say this is the straw that broke the camels back, but not the root of the problem.
![image](https://cloud.githubusercontent.com/assets/16248482/11889706/eb2d8480-a500-11e5-9d2a-fcd6a0237bd5.png)

**Comment by Mykezero** [comment]
Thanks for checking this out for me. I created a new project to test this and called MPPCurrent repeatedly, and the OutOfMemoryException was thrown. I'll have to contact the library author about this problem or think of another way around it.

**Comment by Mykezero** [comment]
Wiccaan has fixed the memory leak for us! I've upgraded the library so this should be fixed.
