### ISSUE TITLE
No distinction between claimed mobs

### ISSUE THREAD

**Issue by Frequency13** [EasyFarm/EasyFarm#158]
The program will not recognize if a mob is claimed by someone else. It will approach a claimed mob, then run back to its way point,over and over again.

**Comment by Mykezero** [comment]
Thanks for the feedback: You're using one of the new versions and not temp fix?

**Comment by Frequency13** [comment]
Using the one you put up a few hours ago.

**Comment by jonii99** [comment]
i feel that, when he put fail,he will move and put , but still fail, move  and put, fail. then, go to next way point

**Comment by Frequency13** [comment]
The entire Targets tab is generally non-functional. No distinction from party-claimed, aggro, unclaimed, or claimed. If its on the target list it will go for it, regardless of state.

**Comment by Mykezero** [comment]
Targeting should be functional now with the switch of API.
