### ISSUE TITLE
EF continues to run after zone

### ISSUE THREAD

**Issue by tresktomte** [EasyFarm/EasyFarm#159]
Hey!

First of all, thanks for an awesome program!

I have been using EF in abyssea and when the timeout has expired and I'm being zoned back, the application continues to run causing the player to just run. It would be nice to have to program pause whenever you're changing zone. I bet the same problem should exist in dynamis as well. Right now it is very easy to get caught using the program as the character keeps running into the wall until you turn the program off.

**Comment by Mykezero** [comment]
I've disabled resuming program on zone and this should fix the problem.
