### ISSUE TITLE
An Exception has occurred.

### ISSUE THREAD

**Issue by jonii99** [EasyFarm/EasyFarm#160]
Object reference not set to an instance of an object. when i set active character, it is up

**Comment by Reiver2285** [comment]
http://www.elitemmonetwork.com/forums/download/file.php?id=66

run this and check what type of VC++ you are missing and install them from microsoft

**Comment by Mykezero** [comment]
@jonii99 This version of the program depends on a new library which requires a few more dependencies than the earlier versions. Try @Reiver2285's suggestion and see if that helps!

**Comment by jonii99** [comment]
thank you, mykezero

**Comment by jonii99** [comment]
thank you Reiver2285

**Comment by Mykezero** [comment]
I'm glad it worked out ^^;
