### ISSUE TITLE
Scholar - Storms

### ISSUE THREAD

**Issue by frenchies5** [EasyFarm/EasyFarm#161]
I have noticed that for SCH. The Storms version II are not available. Is this something I could add myself?

**Comment by Mykezero** [comment]
That means the Windower resource files does not contain information about these spells: You'll need to manually fill out the spells information. 

Depending on the spell you want to use, you'll be using one of the following index values

| Spell Name | Index Value |
|----------------|----------------|
| Sandstorm II  | 857 |
| Rainstorm II | 858 |
| Windstorm II | 859 |
| Firestorm II | 860 |
| Hailstorm II | 861 |
| Thunderstorm II | 862 |
| Voidstorm II | 863 |
| Aurorastorm II | 864 |

Right-click the spell and select "General Options" to set the index value for the spell. You'll also need to setup the mpcosts for the spells, and you can do that from within that screen as well. 

![image](https://cloud.githubusercontent.com/assets/5349608/11919246/1d235ade-a71b-11e5-8d0c-132eada7702a.png)

**Comment by frenchies5** [comment]
I someone managed to update the list in the spells.xml file and it is working. There was nothing listed in that file.

Thank you so much for all your hard work!
