### ISSUE TITLE
Stops working after a few mobs

### ISSUE THREAD

**Issue by colivah** [EasyFarm/EasyFarm#162]
hey just want to say i love this program I have used it for a longtime. I have been trying to get it running again since the DEC update and I have finally got it going however I am experiencing a strange issue where i will hit start it targets a mob kills it and then maybe kills on more then stops completely if I hit pause and run it again it does the same thing is this something I am doing wrong?

**Comment by colivah** [comment]
This is my log 
![Uploading EF.gif…]()

**Comment by Mykezero** [comment]
It might have something to do with issue #154. Since the program can no longer tell whether something is rendered on the screen, it will attempt to attack unspawned mobs like skeletons, bats and elementals.
