### ISSUE TITLE
IsRendered

### ISSUE THREAD

**Issue by SG1234567** [EasyFarm/EasyFarm#164]
//Render0000 specificaly uses 0x200 to check if the object is rendered
            public bool IsRendered(int id) {
                if ((api.Entity.GetEntity(id).Render0000 & 0x200) != 0x200)
                    return false;
                return true;
            }

This method fixed my problems with un-rendered mobs.

**Comment by Mykezero** [comment]
@SG1234567 Thanks for the contribution! I'll give it a quick test later but I've added it to the repository for now. The new changes should be available in releases.
