### ISSUE TITLE
Almost There,  Log Messages

### ISSUE THREAD

**Issue by colivah** [EasyFarm/EasyFarm#166]
well it works a lot better with the latest version but still stops working at some point and I stand there and get killed not sure what causes it to stop but appreciate that it is still being worked on hopefully it will be fully operational again soon. I checked the log and it looks to me that it stopped working after this message in the log "Reached Message Limit.  End of Event Source Error Messages" prior to that in the Log it was showing this message on every mob "Event 500 was called with 1 argument but is defined with 2 parameters" not sure if that helps.

**Comment by Mykezero** [comment]
@colivah There's a few problems here that will need fixing so it may take some time, but fixing these will make the program run for longer. Thanks for the help!

Problems: 
- [x] Fix memory leak within logging. 
- [ ] Find source of Reach Message Limit error.
- [ ] Find source of Event 500 called with 1 ... error.

**Comment by Mykezero** [comment]
The part that's funny is that logging event 500 does not even get called ....

**Comment by Mykezero** [comment]
Alright, the new version should fix the logging issues now. Now only if I can figure out what causes the program to sit there and get people killed.
