### ISSUE TITLE
Pull still work bad

### ISSUE THREAD

**Issue by jonii99** [EasyFarm/EasyFarm#168]
if i set pull magic stone
mob will use stone , fail(cuz move), then wait 4 sec, move, use stone , fail(cuz move)X4,, move to mob,,,,

**Comment by Mykezero** [comment]
Yeah, I'll need to improve casting to prevent the player from moving before a spell or ranged attack is finished.

**Comment by Mykezero** [comment]
This also looks similar to issue #147

**Comment by Mykezero** [comment]
@jonii99 I've changed the casting code; hopefully it works a little better now ^^;
