### ISSUE TITLE
Crash when trying to setup healing

### ISSUE THREAD

**Issue by alkai** [EasyFarm/EasyFarm#169]
Maybe this is just me doing something wrong but when I go to the healing tab and type in cure iv I get an error about faulty input and then easyfarm crashes. Using 1.0.63

**Comment by Mykezero** [comment]
Thanks for the heads up; I'll check it out now. Does the error occur when clicking autofill or after clicking start under the file menu?

**Comment by alkai** [comment]
Autofill, sorry forgot to mention it

**Comment by alkai** [comment]
Found another bug too but Ill make a new comment for it. Thanks for your hard work on this awesome program btw

**Comment by Mykezero** [comment]
This may be fixed in the newer versions of EF.
