### ISSUE TITLE
Battle settings invisible after loading a file

### ISSUE THREAD

**Issue by alkai** [EasyFarm/EasyFarm#170]
For example if I enter some ws settings, save, exit and then start+load, the ws section is blank, but the bot will still use the ws like normal so it's just invisible for some reason, no biggie but a bit annoying when you want to edit stuff. Thanks again

**Comment by Snoopyslr** [comment]
Just change tabs and come back to the original tab.  This will reset the display.

**Comment by alkai** [comment]
You're right, that did work

**Comment by Mykezero** [comment]
Thanks for the reminder on this. It definitely still erks me whenever I load a file that the settings don't appear right away -_-

**Comment by Mykezero** [comment]
Newest version of EF should fix this problem: 
* https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.128
