### ISSUE TITLE
Route not resetting

### ISSUE THREAD

**Issue by mbout4it** [EasyFarm/EasyFarm#177]
are the old function "Reset Navigator" the same as "Stop Player"?  Before I was able to start/restart the route on any portion of the path.  Now I must start at the beginning when I start a clear launch of EF, Also, if I didn't complete the route on EF, I cannot start from the beginning, it wants to pickup where the route stop/paused last.  The only way I can get it to route again is either resume where it stopped or close out the app completely.  

Can we either make it so can reset and detect which portion of the route it's located and continue, or have a function to reset the navigator so it starts from the beginning again.

**Comment by Mykezero** [comment]
Yeah, Reset Navigator and Stop Player are the same. I've re-added the code for resuming to the closest position. This way, when the program is paused, it will pick the closest spot and resume from there. Hopefully this solved the problem ^^;

**Comment by Mykezero** [comment]
Issue #178 has the information regarding the new issue with route following.
