### ISSUE TITLE
targeting priority when mob aggroed

### ISSUE THREAD

**Issue by mbout4it** [EasyFarm/EasyFarm#179]
Can you set it so when you have multiple mob that have aggro on you, it picks the mob on your target list first then to mobs that's not on your list?  Good example would be BST mob and their pets, I would rather kill the BST themselves that's on my list over their pets that's not on the list.  So simply have it check for mobs on the target list then move to non-targeted mob would work.

**Comment by Mykezero** [comment]
Thanks for the suggestion. This would be good for the situation where you're fighting a Yagudo with an elemental pet that will despawn when the master is killed. I'll see what I can do about adding it ^^;

**Comment by mbout4it** [comment]
The workaround I did was added pet names to IGNORED tab.  I should had use that from the start. You can consider this request complete.
