### ISSUE TITLE
Multiple Aggro-ed Targets

### ISSUE THREAD

**Issue by SG1234567** [EasyFarm/EasyFarm#180]
If I try to farm an area where the targets link or aggro (Escha Zitah Efts) I will often get multiple targets attacking me at once with the same name. When this happens it will occasionally lose track of who its fighting. It will engage one target, but at the same moment lock on to a separate target. This causes the bot to get killed because it is looking in the wrong direction. 
I was wondering if its a possibility to re-engage if there is a "Unable to see target" message multiple times?

**Comment by Mykezero** [comment]
Have you tried disabling auto-target in game? This could create the situation where the program is targeting one mob, but really should be killing the other.

**Comment by jonii99** [comment]
ya, use /autotarget off will fix it

**Comment by SG1234567** [comment]
This is a much more complex issue than this. my simple fix is to have a tank trust always out if i plan to run in an area with aggro. This allows me to have less aggro from current target and adds.

From my testing is seems to be a problem with their distance to the character. this happens in two situations. 
1) I have multiple targets aggroed (both from behind so auto attack is not an issue) on my character while fighting a third. Once I kill the original one, the program chooses the closest and engages. At the same time that I move to face the new mob, I also get closer to the other target. This causes me to focus on the closer target but attack a different one. 
2) I have a detect and wander range and two enemies in range. I will run to the closer one, while on my path to get to it I engage it but never hit it. The target then walks out of wander range, but not engaged range. My character then focus on mob two while engaged with mob 1 and effectively does not do anything at all.

**Comment by Mykezero** [comment]
#222 Might fix this problem.
