### ISSUE TITLE
1.0.69 not working after feb patch

### ISSUE THREAD

**Issue by SG1234567** [EasyFarm/EasyFarm#188]
After selecting my characters name it does not display correctly and never is able to start.
on this line is where its breaking for me 
`_cancellation.Token.ThrowIfCancellationRequested();`

Its late and this was a fast debug. I'll do more digging tomorrow.

It also looks to be a fface issue as your process.id looks correct here but the output is not complete:
`var fface = MemoryWrapper.Create(process.Id);`

**Comment by Mykezero** [comment]
Thanks for the heads up on the patch; For now you might be able to get the application working by dropping the new version of library into EasyFarm's folder. 

http://ext.elitemmonetwork.com/downloads/eliteapi/

You just need to delete the old version of the EliteAPI.dll file and replace it with the new version. 

For the fface variable, it actually creates an instance of the eliteapi wrapper; I just haven't gotten around to changing the variable name just yet >.<

`var fface = MemoryWrapper.Create(process.Id);`

Hopefully the application works after replacing the old file with the new one; I'll try to repackage the program later with the new library changes.

**Comment by Nasteff** [comment]
replaced old file with that new one from link.  seemed to work.

**Comment by Jurbie** [comment]
This is currently only working at a minimal capacity. I have tried running this in dynamis just to have it run for about 5min then pathing stops, stops engaging, and stops attacking agro. its as if it just shuts itself off after a random amount of time for no reason. I am not sure if something is triggering this, or if it just has a bug after the update.

**Comment by Jurbie** [comment]
It is also having a small issue where it will engage a mob, but for some reason wont be actually hitting it, If I force it to back up one step and what appears to be "correcting the line of sight" it will start to attack it. I am not getting the error message saying "you cannot see your target" but it is acting as if it is. When the program is just unresponsive and idle, if I click pause then start it will start running again only to stop running a short time later.

**Comment by Jurbie** [comment]
I would also like to note that its having issues when hung up on terrain. It doesn't have an engaged no hit, or follow not attack. I am seeing many times when it tries to engage a mob on the other side of a terrain obstacle and will just run at it until you get agro and die running in place. I have tried to use ranged job abilities and the ranged weapon function but this only solves the issue if the mob is one that cannot attack at distance. If the mob on the other side at distance is a mage/nin/ranger, it will just run in place at stuck on the structure until agro ends up killing you. Does EF have a time out function where it will only try to be engaged to a mob for so long without hitting it before it moves on to the next target? How can we incorporate some sort of function like this in if we do not already have it.

**Comment by Jurbie** [comment]
didnt even get to finish the above posts before it shut itself off again :(

**Comment by Jurbie** [comment]
Just noticed that the routing function is bugged as well. I am going to try to explain this the bast I can. When I am running on a route and engage a mob and get agro and fight a few mobs it takes it slightly off the route. No biggie, but when it returns to the route rather then proceeding to the next point it acts as if it just hit the end of the route and starts going back the opposite direction. It is if I am going on the road (route) kill some mobs that make me go off route, then flip a U turn and go back where I just came. This keeps me killing the same set of mobs and never actually getting all the way through my route.Also I am not sure if this is why I never get a full "loop" in my route or not. It seems when I hit the last point in the route it does an about face, or U turn rather then running to route point 1.

Example: What I would like to see
1,2,3,4,5,1,2,3,4,5
^ the above shows it moving from the last point in the route to the first point in the route to complete the loop. 

Example: What I am seeing
1,2,3,4,5,4,3,2,1,2,3,4,5,4,3,2,1 
It just turns around when hitting the lsat point even if the first point is right in front of it. Running a short route and ending where I started should just have it loop. Instead it turns around and goes back where it came from >_<! regardless of where I start/stop its not looping.

**Comment by Mykezero** [comment]
I've repackaged the program with the newest version of elitemmo api but I won't be able to test it until tomorrow morning.

**Comment by mbout4it** [comment]
using newest version #44, so far no issues for about a week now.

**Comment by Mykezero** [comment]
Thanks for the update @mbout4it . I'm glad it's working now.

**Comment by Moldtech** [comment]
I have the crashing error pop up when trying to select a character instance:
![capture](https://cloud.githubusercontent.com/assets/17488182/13342811/69871eb0-dc13-11e5-8d8a-38973a66f893.PNG)
