### ISSUE TITLE
can't use VI magic

### ISSUE THREAD

**Issue by jonii99** [EasyFarm/EasyFarm#189]
please help,all VI magic aren't support,can't add

**Comment by Mykezero** [comment]
You'll need to update the index value manually to get Tier VI magic to work correctly. These index values are located under the "General Options" right click menu. To get the spells working you'll need to: 

1. Right clicking on an action.
2. Select "General Options"
3. Find Index, and enter in the value.

The value of the index will depend on the spell you want to use which can be looked up in this list: 

Index | Spell Name
---|---
856 | Endark II
855 | Enlight II
854 | Water VI
853 | Thunder VI
852 | Stone VI
851 | Aero VI
850 | Blizzard VI
849 | Fire VI

Here's what the result will look like after updating the index value:

![image](https://cloud.githubusercontent.com/assets/5349608/13161754/d5a969b4-d66d-11e5-9ff6-9c569ed95528.png)

Hopefully this helps! ^^;

**Comment by jonii99** [comment]
thank you , get it

**Comment by jonii99** [comment]
it is auto skip to unknown , not magic
