### ISSUE TITLE
Keep dying

### ISSUE THREAD

**Issue by Mazzolani** [EasyFarm/EasyFarm#190]
When I get aggro from about 5-6 Mobs. It seems that I'm not facing the mob i have targeted.

**Comment by mbout4it** [comment]
make sure you turn off auto target with " /AutoTarget OFF"

**Comment by Mykezero** [comment]
Yes, definitely make sure that autotarget is off. I'll be looking into some of the causes in issue #180 where multiple mobs aggro but the character tries to attack things that it's not looking at.

**Comment by Mykezero** [comment]
#222 Might fix this problem
