### ISSUE TITLE
EasyFarm Support

### ISSUE THREAD

**Issue by Mykezero** [EasyFarm/EasyFarm#192]
### Support Ticket

Use this ticket for asking questions or giving feedback about the program. You can pretty much talk about anything in this issue; alternatively, you can use the [EasyFarm's post](http://www.elitemmonetwork.com/forums/viewtopic.php?f=10&t=394) on EliteMMO Network forums for as well.

**Comment by Moldtech** [comment]
I get this crash error consistently when trying to select a character instance in EF:
![capture](https://cloud.githubusercontent.com/assets/17488182/13343371/ed6fd07c-dc19-11e5-9869-238c0baa0a8d.PNG)
EF hasn't worked for me since the last major FFXI update.

**Comment by Mykezero** [comment]
It looks like the program isn't able to load the EliteApi library file. Have you tried running the [dependency checker)(http://www.elitemmonetwork.com/forums/viewtopic.php?f=28&t=329) on EliteMMO to make sure you have everything needed to run the program? 

Also, make sure that you are running the program as an administrator so that it can properly load everything it needs to run. Lastly, make sure that the EliteAPI.dll file actually exists within EasyFarm's directory (maybe antivirus could have sandboxed or quarantined that file).

**Comment by Moldtech** [comment]
Hello,

These are the files in my EasyFarm folder and the resources folder when I attempt to select a character instance and it gives the EliteAPI.dll error:





As you can see, that EliteAPI.dll file is there, directly underneath the EasyFarm application file. I’m running as Administrator. I run everything as Administrator. I have no idea why it’s saying it can’t be located.

Also, I tried to run that EliteMMO.SystemCheck that you supplied a link to and it also gives a critical, crashing error. When attempting to run that file, I get this error:





It appears that it is not compatible with my version of Windows or something. Compatibility troubleshooter is finding no Windows version issues with it nor is it finding any issues with EasyFarm. I’m running with this version of Windows:






I’m at a loss as to why none of it is working for me. It’s the same thing even after deleting it all, re-downloading it fresh from GitHub (https://github.com/EasyFarm/EasyFarm/releases), and starting from scratch. Version 1.0.70 and 1.0.71 gives this same error. Version 1.0.69 gives the error below with or without the EliteAPI.dll file updated:





Your assistance is greatly appreciated.

Thank you,
Mold

**Comment by Mykezero** [comment]
@Moldtech I can't see the images for some reason. What version of Windows are you using? EasyFarm isn't compatible with Windows XP but should work on Vista, 7, 8, 8.1 and 10 versions.

**Comment by Moldtech** [comment]
Windows 10 Pro

**Comment by tacheride** [comment]
Is there a way to add spells or items to the resources? I'm specifically looking for Capacity Ring and Aspir 3. Thanks!

**Comment by Moldtech** [comment]
Hello,

I'm not the developer and am unable to give you a proper official solution to your issue.

Unofficially, you can add those items to the files if they're not there easily with a program called Notepad++ but I don't know for certain if the program will acknowledge your additions or not. Personally, I think it will but I cannot guarantee it or check it to confirm it.

I'm having an issue myself and am unable to select a character to run the program with. Program crashes instantly upon character selection.

Try this address:

notifications@github.com

Take care,
Moldtech

**Comment by Moldtech** [comment]
Hello,

I was just checking to see if there was a solution to my issue or not within EasyFarm.

The issue wherein selecting a character instantly crashes the program. Last I heard was the email directly below and I responded with "Windows 10 Pro." 

Thank you,
Moldtech

**Comment by Moldtech** [comment]
Oh! My email replies have been leaving posts on the thread. How slick! ^^

Someone able to assist me yet?

**Comment by Mykezero** [comment]
It's very strange the the system checker would fail as well. I'll check out what files you'll need to run the program and post links to them here so that you can run them to ensure that all those requirements are met. Sorry for the very late response >.<

**Comment by Moldtech** [comment]
Hello,

Indeed. The system checker won’t load whatsoever on my PC. A yellowish-gold Windows AERO-like pop-up comes up saying:

“This app can’t run on your PC. To find a version for your PC, check with the software publisher.”

Just tried the newer versions of both, EasyFarm and the system checker that is posted and get the same errors. My EasyFarm folder contains, in this order:

resources folder containing these XML files:     abils, areas, items_armor, items_general, items_weapons, spells, and status
EasyFarm application file
EliteAPI.dll
EliteMMO.API.dll
MahApps.Metro.dll
MemoryAPI.dll
Microsoft.Practices.ServiceLocation.dll
Microsoft.Practices.Unity.Configuration.dll
Microsoft.Practices.Unity.dll
Microsoft.Practices.Unity.RegistrationByConvention.dll
Newtonsoft.Json.dll
NLog.dll
Prism.dll
Prism.Unity.Wpf.dll
Prism.Wpf.dll
System.Windows.Interactivity.dll

When trying to select a character instance to use it with I get that error:

“Unable to load DLL ‘EliteAPI.dll’: The specified module could not be found. (Exeption from HResult: 0x8007007E)”

and then crashes closed.

Thank you for looking into my issue,
Mold

**Comment by Moldtech** [comment]
Hello,

Issue, resolved! I was missing Microsoft Visual Runtime C++ 2015. Upon installing that, no error remained!

Thank you,
Mold

**Comment by Mykezero** [comment]
@Moldtech I'm glad it's working for you now. I'm also sorry that I couldn't have been of more help to you >.<

**Comment by Bastokan** [comment]
Firstly, would like to say great work on this application. Going to make things a lot easier for a great many things. Only ran into some small snag that I'd like to ask about. Occasionally while engaging one target, it will randomly swap to another and just gets stuck that way. Have to manually pause and turn around to kill the first mob (Note that the target will show the second mob even though it is engaged on the first one still.) Wondering if there might be any suggestions to fix this issue. Thank you in advance and keep up the good work!

**Comment by Mykezero** [comment]
Definitely turn off autotarget if you haven't done so already, so that EasyFarm has complete control over targeting.
```
/AutoTarget OFF
```
This should at least minimize that problem, but as reported in issue #180, EF will still occasionally run into that situation. I'll see what I can do about this problem

**Comment by Moldtech** [comment]
Hello,

This glitch is happening to us all. We’ve found that raising the global timer to at least 2000 assists in reducing the error. 

Mold

**Comment by Mykezero** [comment]
@Moldtech Whoops, I forgot to respond. Very good suggestion for reducing the rate of that error!

Increasing the global timer does sound like it would reduce the occurrence of that problem, but would cause your character to wait 2 seconds between some interactions which is undesirable. 

It's far from the ideal solution, and I'm hoping to add some kind of synchronization between targeting / looking at a mob and engaging it.

**Comment by SG1234567** [comment]
Hello Mykezero I've been enjoying your program for a while now and wanted to say great job, and all your work is much appreciated!

I have an enhancement that i am wondering what it would take to get it in the program. I would like for the bot to open boxes. 
1. Escha brown boxes. there is a very limited amount of variety in them (not locked, item selection)
2. Time extensions/pop items in Abyssea (use of keys, add all to spoils)

I know there are ID's for the boxes that it currently ignores. I'm just not sure how to integrate it, make it select it, and then select an item.

**Comment by freaker4444** [comment]
I don't mean to be to an old post but this is the exact same problem I am having right now. System checker shows everything is green, I can visualize the alleged missing file in the east farm folder. I have even wiped it and reloaded several times. Any assistance would be amazing.

**Comment by Moldtech** [comment]
Download and install:

Microsoft Visual Runtime C++ 2015

Mold

**Comment by freaker4444** [comment]
I have it installed already but I will try removing it and installing again.

**Comment by freaker4444** [comment]
Now it just keeps telling me that it could not install and that a system restart is required. Would it help if I posted the log of the error?

**Comment by Moldtech** [comment]
Did ya restart?

**Comment by freaker4444** [comment]
Yes. No luck.

**Comment by Moldtech** [comment]
Perhaps Mykezero can assist you whenever he comes across this post. 

Maybe send him an email in full detail of your exact issue to aid him in understanding the issue at hand.

Mold

**Comment by Mykezero** [comment]
@freaker4444 Have you tried installing [Microsoft .NET Framework 4.5](https://www.microsoft.com/en-US/Download/details.aspx?id=30653)?

**Comment by Barbanera87** [comment]
Hey, I solved this installing vc++ 2010,2012,2013,2015 x86 version... even with 64bit Windows I solved installing all those x86 vc++.

**Comment by Mykezero** [comment]
Hi @zmann408 Try unblocking all of the Ninject dll files, by right clicking them and selecting "Unblock"
[Example of how to unblock a file](https://github.com/EasyFarm/EasyFarm/issues/328#issuecomment-385296427)

You'll want to unblock these three files: 
* Ninject.dll
* Ninject.Extensions.Conventions.dll
* Ninject.Extensions.Factory.dll

**Comment by adeptio** [comment]
Hello, I'm trying to figure out the best way to use a Capacity Ring via the program.  

In my case the program recognizes the item, uses it, then stalls without an error message. I am using the status on !Dedication - which I believe is the correct term.  The action is in the 'End' bracket.

Thank you!  And thanks for fixing the targeting issue in the latest release, very helpful.

**Comment by ordorf2000** [comment]
I have a problem with the program, I think simply in the battle option, a weapon skill, whatever it is, does it well but after killing 2 enemies I always get an error in all kinds of actions and I no longer continue fighting because that error causes

**Comment by Moldtech** [comment]
My apologies, for I have long since been retired from FFXI since Jan 2017.

However, knowing that you are still going strong slams me in the feels!

Had it not been for having a heart attack from trying to keep up with a 12-hour shift schedule and playing FFXI, I would still be playing as well

Good luck to finding a solution to your dilemma! Hopefully someone sees your posting and responds in kind 🙂

Good luck,
Moldtech / Autotech

------ Original Message ------

**Comment by ordorf2000** [comment]
I hope you are better and thank you for taking the trouble to see my message


________________________________
De: Moldtech <notifications@github.com>
Enviado: viernes, 12 de febrero de 2021 11:04 p. m.
Para: EasyFarm/EasyFarm <EasyFarm@noreply.github.com>
CC: ordorf2000 <ordorf_ffxiv@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [EasyFarm/EasyFarm] EasyFarm Support (#192)


My apologies, for I have long since been retired from FFXI since Jan 2017.

However, knowing that you are still going strong slams me in the feels!

Had it not been for having a heart attack from trying to keep up with a 12-hour shift schedule and playing FFXI, I would still be playing as well

Good luck to finding a solution to your dilemma! Hopefully someone sees your posting and responds in kind 🙂

Good luck,
Moldtech / Autotech

------ Original Message ------

**Comment by freaker4444** [comment]
The manners and consideration on display in this email chain give me hope for the world. Two strangers showing nothing but respect for one another. 👌

**Comment by Josafath07** [comment]
I have an issue with EasyFarm.

When launched, after some minutes I just an error at the bottom which says "An error Occured" and the program stops.

The Logs have this information (sorry for Spanish):

2022-12-16 15:13:47.6659 EasyFarm.Logging.NLogTextFileLogger EasyFarm Started ...
2022-12-16 15:18:12.5715 EasyFarm.Logging.NLogTextFileLogger FSM error
System.InvalidOperationException: La colección se modificó después de crear una instancia del enumerador.
   en System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   en System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en EasyFarm.States.BattleState.ShouldRecycleBattleStateCheck() en C:\projects\easyfarm\EasyFarm\States\BattleState.cs:línea 81
   en EasyFarm.States.BattleState.Run() en C:\projects\easyfarm\EasyFarm\States\BattleState.cs:línea 70
   en EasyFarm.States.FiniteStateMachine.RunStateMachine() en C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:línea 171
   en EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() en C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:línea 99

When trying to go to that C: file it does not exist in my pc. Any ideas how to fix this?

**Comment by Mykezero** [comment]
Closing for now, will take all comments from this issue and will create separate issues for these piecs
