### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by Nasteff** [EasyFarm/EasyFarm#198]
will not cast geo-malaise in pull section anymore, tried in battle doesnt work either

**Comment by Nasteff** [comment]
was having issues casting spells in the pull section, now the pull section is working but wont fast spells in battle section

**Comment by Mykezero** [comment]
Thanks, is this with the updated EliteAPI files?
I working on updating the program now with the latest dll files which should be in releases soonish.

**Comment by Mykezero** [comment]
The program has been updated, and is hopefully working now.
