### ISSUE TITLE
Blue magic issue

### ISSUE THREAD

**Issue by Haltrius** [EasyFarm/EasyFarm#204]
Hello 

Everytime i try to set a blu spell such as foot kick or helldive, the autofill give me error and closes the program. The only one it accets is Pollen but in game it gives me error. Is there a special way to set blu spells?

**Comment by Mykezero** [comment]
Nothing special has to be done to create those spells; just typing the spell name and clicking Autofill should work. Very strange that the program doesn't crash for creating pollen, but crashes for the other spells. Does the program say what the error is before crashing?

If you haven't done so already, try running the EliteMMO System Checker tool to check for any missing packages: 
* [EliteMMO System Checker](http://www.elitemmonetwork.com/forums/viewtopic.php?f=28&t=329)

In addition, you'll want to make sure you have .Net 4.5 installed as well, which you can find here: 
* [Microsoft .Net 4.5](https://www.microsoft.com/en-US/Download/details.aspx?id=30653)

You'll also want to make sure you are running this program as an administrator by right clicking the EasyFarm.exe file, and selecting Run as Administrator.

**Comment by Haltrius** [comment]
I have framework up to date and all required files. I run the program as administrator. When it crashes, it says error in the string. I translate directly from French as my computer is set in French. Windows 10.
In addition to the crash, when I reload it, it crashes windower. I have to restart windower again.

**Comment by Mykezero** [comment]
Yeah, it might not like the computer being set to French; when I was building the program, I didn't take localization into account so that definitely could cause an error. Hopefully I can set my computer to French, and reproduce this problem. Thanks for the updated information!

**Comment by Haltrius** [comment]
Ok. I'll wait for your feedback then after you try.  As it is a family computer, I cannot turn it into English.

**Comment by Mykezero** [comment]
Yeah, it's definitely something I should be handling on my end; The program should just work as is.

**Comment by Mykezero** [comment]
I've fixed the problem, and I'm working on packaging it up now. The new version should be in releases soon. I haven't tested it completely with the game running, so It may break in another place; if that happens just let me know!

**Comment by Haltrius** [comment]
Nice. Can't wait for the new version. Thanks a lot.

**Comment by Mykezero** [comment]
The new version is available now: 
https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.81
