### ISSUE TITLE
August SE Update

### ISSUE THREAD

**Issue by bassmanseidell** [EasyFarm/EasyFarm#210]
Seems like easyfarm isn't working after the most recent update. It does not connect to the character.

**Comment by Mykezero** [comment]
@bassmanseidell Thanks for the heads up; once the new updates to the EliteMMO API are available, I'll push out an update as soon as possible!

**Comment by bassmanseidell** [comment]
I updated both api's to the may 2016 files and it is working again. lol right in the for the cp campaign

**Comment by Mykezero** [comment]
@bassmanseidell Sorry for my late response. I've finally gotten around to updating the EliteAPI files as well as updating the resource files. My bad T_T
