### ISSUE TITLE
can't set magic

### ISSUE THREAD

**Issue by jonii99** [EasyFarm/EasyFarm#217]
when i put dia to pull action, and press auto-fill , still nothing, what happen?

**Comment by jonii99** [comment]
EasyFarm 1.0.84

**Comment by Mykezero** [comment]
Hi @jonii99 , 

You wouldn't happen to be trying to edit the menu for pull itself, would you? Try expanding the pull category and editing new action instead. 

The screen should look a little like this when finished: 

![image](https://cloud.githubusercontent.com/assets/5349608/18586328/2302e4fc-7bea-11e6-8332-08b16298b227.png)

**Comment by jonii99** [comment]
i was set Dia, and press auto-fill, there is not magic and enemy. dont know. old version was ok on that autofill,do  i need install any new plugin to make that work?
btw  the new version can't use magic at sometimes, not all the times.version1083

**Comment by jonii99** [comment]
![qq 2016a](https://cloud.githubusercontent.com/assets/13082910/18608266/4ca65a36-7d17-11e6-8e44-6c9cb1645178.jpg)
![qq 2016b](https://cloud.githubusercontent.com/assets/13082910/18608267/4d94fe98-7d17-11e6-8c36-19bfae7a20e0.jpg)

**Comment by Mykezero** [comment]
Try expanding that Pull category that I've highlighted in red, select the "New Action" item under it, and then try entering Dia's information for AutoFill to work. 

![image](https://cloud.githubusercontent.com/assets/5349608/18612448/2ce3ef7c-7d28-11e6-87e7-4a093c3c66f7.png)

Hopefully that helps a little bit ^^;

**Comment by jonii99** [comment]
thank you ,my mistake. sorry, btw,, great program ^^

**Comment by Mykezero** [comment]
@jonii99 I'm glad this worked out! ^^
