### ISSUE TITLE
Issue with targeting after killing a mob

### ISSUE THREAD

**Issue by staleyx** [EasyFarm/EasyFarm#220]
Character seems to run around and engage then disengage after killing 2 mobs. I have paths cleared with no path loaded. Is this something with wander or detection distance? I'm in a small enough area where there are always 5-6mobs.

**Comment by Mykezero** [comment]
I think the new object avoidance code I added is causing this. I've pushed a new version of the program that will make that code optional for now. You'll be able to toggle it on or off in the settings table. I haven't tested it yet, but when I get home I'll give it a good run down.
