### ISSUE TITLE
Engaging

### ISSUE THREAD

**Issue by raise334** [EasyFarm/EasyFarm#224]
I'm having an issue where my character will not engage any mobs. It just targets them runs up to them and sits there or follows them and does not engage them? Do I have to put something in for it to engage them?

**Comment by Snoopyslr** [comment]
I'm having the same issue.  Character will not engage.  I'm fighting worms and my character will engage when the worm burrows and reappears.

**Comment by Snoopyslr** [comment]
Found something else out.  If I target off my currently targeted target (huehue) it will engage.  Hence why when the worm depops I engage.  I do have auto-targeting off.  Seems to be when EasyFarm targets a mob immediately after killing one.

**Comment by theken3** [comment]
After the November update, my character will not engage mobs. The log shows it will target them, but it does not lock on, run up to them or anything else. I did download the latest (1.0.89). Recommendations?

**Comment by L57703** [comment]
The 1.0.89 version is broken. Use 1.0.88 or older versions till its fixed.

**Comment by Mykezero** [comment]
I reverted those bad changes from the last update. I would recommend using either 1.0.88 or 1.0.90; they are both the same functionality wise.
