### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by L57703** [EasyFarm/EasyFarm#227]
After the update on 12/13/2016 it will crash when you try to select the character process.

**Comment by slowenvy** [comment]
Im also having the same issue! Help us plz 😨 i miss easy farm

**Comment by Mykezero** [comment]
Atom0s updated the EliteAPI a few hours ago. I'll try to get a new release out soon with the new updates.

**Comment by gymshark89** [comment]
Yay! thats good to hear

**Comment by slowenvy** [comment]
Downloaded the new .dll its working great! Thank you for the quick fix! 😃

**Comment by Mykezero** [comment]
I'm glad it's working now! ^^
