### ISSUE TITLE
EasyFarm not detecting Character

### ISSUE THREAD

**Issue by gymshark89** [EasyFarm/EasyFarm#233]
When I go to click select character it pulls up my character list, but nothing happens when I select my character. It doesnt crash or anything it just does not register my character being selected or anything. After 1/9/2017 update.

**Comment by nubt** [comment]
same here

**Comment by Captainretard** [comment]
Same here :(

**Comment by Mykezero** [comment]
I've pushed a new version that should include Atom0s's new updates to the EliteAPI. Hopefully that gets the program working again.

**Comment by gymshark89** [comment]
its working great!

**Comment by Mykezero** [comment]
Thanks, glad to hear it!

**Comment by gymshark89** [comment]
Thank you so much Mykezero for all ways being on top of this and getting to the solution ASAP.
