### ISSUE TITLE
Weaponskill issues

### ISSUE THREAD

**Issue by Sageomithas** [EasyFarm/EasyFarm#240]
Was having issues with the program using certain weaponskills when I loaded them in the weaponskill tab, specifically Ranged WS's and Sword WS's.  

I found a way to get them to work properly is to put them in the Battle tab, not sure if this is a problem that can be fixed easily or not.

**Comment by Mykezero** [comment]
Which weapon skills were you having a problem with? Very strange that they would work in one tab, but not the other.

**Comment by Sageomithas** [comment]
Wildfire and Savage Blade, I used all of the same information (auto-fill) in both battle and weaponskill tabs.

**Comment by Mykezero** [comment]
There have been a lot of changes to EF since this has occurred: 

Newest Version: https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.127

Please let me know if this is still a problem.
