### ISSUE TITLE
Character Keeps Running 

### ISSUE THREAD

**Issue by nubt** [EasyFarm/EasyFarm#243]
If I try pausing while it's running it's route it'll keep running in that direction.  I have to start EF again and pause it's fighting a mob to prevent this from happening.

**Comment by Mykezero** [comment]
I might have messed up the pathing code in the last update. This should be pretty easy to fix though! Sorry for the trouble ^^; I'm should have some time to fix these problems today.

**Comment by nubt** [comment]
Yeah, following characters stutter every now and then when they're running as well like they step forward and back a couple times seemingly randomly.

**Comment by Mykezero** [comment]
Actually, I didn't test following characters after these changes >.<. I'll check to see If I've broken that functionality as well!

**Comment by Mykezero** [comment]
I've pushed out a new version that should stop the player from running after pause is pressed, but I wasn't able to find the problem with following. Anything special I need to do to trigger that?
