### ISSUE TITLE
.101 does nothing?

### ISSUE THREAD

**Issue by Altalus** [EasyFarm/EasyFarm#244]
So, it's probably something I did but I can't seems to make it work anymore... I'm using the app as a bot to duo, so normally the bot is setup to be the tank while I cure.

The following profile used to work but now the bot does nothing. It does not engage, or use abilities, or weapon skills. I made sure to start as admin and I can see, and select, the right Window for that character.

Spec:
- Client: Ashita 
- Server: Private server
- Windows 10 pro

The .eup file I use:
`{"AggroFilter":false,"BattleLists":[{"Name":"Start","Actions":[{"Ability":{"Id":0,"Index":0,"English":null,"Japanese":null,"MpCost":0,"TpCost":0,"Alias":null,"AbilityType":0,"Prefix":null,"Postfix":"<t>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":0,"Type":null,"SkillType":0,"Skill":null,"ElementType":0,"Element":null,"TargetType":0,"Targets":null,"IsValidName":false,"RangedCommand":" <t>","ActionCommand":" \"\" <t>","Command":" \"\" <t>"},"AbilityType":0,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":false,"LastCast":"0001-01-01T00:00:00","Name":null,"PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0}]},{"Name":"Pull","Actions":[{"Ability":{"Id":0,"Index":0,"English":null,"Japanese":null,"MpCost":0,"TpCost":0,"Alias":null,"AbilityType":0,"Prefix":null,"Postfix":"<t>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":0,"Type":null,"SkillType":0,"Skill":null,"ElementType":0,"Element":null,"TargetType":0,"Targets":null,"IsValidName":false,"RangedCommand":" <t>","ActionCommand":" \"\" <t>","Command":" \"\" <t>"},"AbilityType":0,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":false,"LastCast":"0001-01-01T00:00:00","Name":null,"PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0}]},{"Name":"Battle","Actions":[{"Ability":{"Id":547,"Index":5,"English":"Provoke","Japanese":"挑発","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<t>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":50,"Targets":"Enemy","IsValidName":true,"RangedCommand":"/jobability <t>","ActionCommand":"/jobability \"Provoke\" <t>","Command":"/jobability \"Provoke\" <t>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":true,"LastCast":"0001-01-01T00:00:00","Name":"Provoke","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0},{"Ability":{"Id":544,"Index":2,"English":"Warcry","Japanese":"ウォークライ","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<me>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":1,"Targets":"Self","IsValidName":true,"RangedCommand":"/jobability <me>","ActionCommand":"/jobability \"Warcry\" <me>","Command":"/jobability \"Warcry\" <me>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":true,"LastCast":"0001-01-01T00:00:00","Name":"Warcry","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0},{"Ability":{"Id":549,"Index":14,"English":"Dodge","Japanese":"回避","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<me>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":1,"Targets":"Self","IsValidName":true,"RangedCommand":"/jobability <me>","ActionCommand":"/jobability \"Dodge\" <me>","Command":"/jobability \"Dodge\" <me>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":true,"LastCast":"0001-01-01T00:00:00","Name":"Dodge","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0},{"Ability":{"Id":548,"Index":13,"English":"Focus","Japanese":"集中","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<me>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":1,"Targets":"Self","IsValidName":true,"RangedCommand":"/jobability <me>","ActionCommand":"/jobability \"Focus\" <me>","Command":"/jobability \"Focus\" <me>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":true,"LastCast":"0001-01-01T00:00:00","Name":"Focus","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0},{"Ability":{"Id":738,"Index":8,"English":"Retaliation","Japanese":"リタリエーション","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<me>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":1,"Targets":"Self","IsValidName":true,"RangedCommand":"/jobability <me>","ActionCommand":"/jobability \"Retaliation\" <me>","Command":"/jobability \"Retaliation\" <me>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":false,"LastCast":"0001-01-01T00:00:00","Name":"Retaliation","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0},{"Ability":{"Id":545,"Index":3,"English":"Defender","Japanese":"ディフェンダー","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<me>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":1,"Targets":"Self","IsValidName":true,"RangedCommand":"/jobability <me>","ActionCommand":"/jobability \"Defender\" <me>","Command":"/jobability \"Defender\" <me>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":true,"LastCast":"0001-01-01T00:00:00","Name":"Defender","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0},{"Ability":{"Id":546,"Index":4,"English":"Aggressor","Japanese":"アグレッサー","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<me>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":1,"Targets":"Self","IsValidName":true,"RangedCommand":"/jobability <me>","ActionCommand":"/jobability \"Aggressor\" <me>","Command":"/jobability \"Aggressor\" <me>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":false,"LastCast":"0001-01-01T00:00:00","Name":"Aggressor","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0},{"Ability":{"Id":543,"Index":1,"English":"Berserk","Japanese":"バーサク","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<me>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":1,"Targets":"Self","IsValidName":true,"RangedCommand":"/jobability <me>","ActionCommand":"/jobability \"Berserk\" <me>","Command":"/jobability \"Berserk\" <me>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":true,"LastCast":"0001-01-01T00:00:00","Name":"Berserk","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0}]},{"Name":"End","Actions":[{"Ability":{"Id":0,"Index":0,"English":null,"Japanese":null,"MpCost":0,"TpCost":0,"Alias":null,"AbilityType":0,"Prefix":null,"Postfix":"<t>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":0,"Type":null,"SkillType":0,"Skill":null,"ElementType":0,"Element":null,"TargetType":0,"Targets":null,"IsValidName":false,"RangedCommand":" <t>","ActionCommand":" \"\" <t>","Command":" \"\" <t>"},"AbilityType":0,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":false,"LastCast":"0001-01-01T00:00:00","Name":null,"PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0}]},{"Name":"Healing","Actions":[{"Ability":{"Id":550,"Index":15,"English":"Chakra","Japanese":"チャクラ","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<me>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":1,"Targets":"Self","IsValidName":true,"RangedCommand":"/jobability <me>","ActionCommand":"/jobability \"Chakra\" <me>","Command":"/jobability \"Chakra\" <me>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":true,"LastCast":"0001-01-01T00:00:00","Name":"Chakra","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0}]},{"Name":"Weaponskill","Actions":[{"Ability":{"Id":551,"Index":16,"English":"Boost","Japanese":"ためる","MpCost":0,"TpCost":0,"Alias":"","AbilityType":8,"Prefix":"/jobability","Postfix":"<me>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":3,"Type":"JobAbility","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":1,"Targets":"Self","IsValidName":true,"RangedCommand":"/jobability <me>","ActionCommand":"/jobability \"Boost\" <me>","Command":"/jobability \"Boost\" <me>"},"AbilityType":8,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":true,"LastCast":"0001-01-01T00:00:00","Name":"Boost","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0},{"Ability":{"Id":53,"Index":900,"English":"Crescent Moon","Japanese":"クレセントムーン","MpCost":0,"TpCost":1000,"Alias":"","AbilityType":5,"Prefix":"/weaponskill","Postfix":"<t>","CastTime":0.0,"Recast":0.0,"Distance":0.0,"CategoryType":1,"Type":"WeaponSkill","SkillType":17,"Skill":"Ability","ElementType":1298,"Element":"None","TargetType":50,"Targets":"Enemy","IsValidName":true,"RangedCommand":"/weaponskill <t>","ActionCommand":"/weaponskill \"Crescent Moon\" <t>","Command":"/weaponskill \"Crescent Moon\" <t>"},"AbilityType":5,"AutoFillCommand":{"IsActive":false},"Distance":3.0,"IsEnabled":true,"LastCast":"0001-01-01T00:00:00","Name":"Crescent Moon","PlayerLowerHealth":0,"PlayerUpperHealth":0,"Recast":0,"StatusEffect":"","TargetLowerHealth":0,"TargetName":"","TargetUpperHealth":0,"MPReserveLow":0,"MPReserveHigh":0,"TPReserveLow":0,"TPReserveHigh":0,"TriggerOnEffectPresent":false,"UsageLimit":0,"Usages":0}]}],"ClaimedFilter":false,"DetectionDistance":17.0,"GlobalCooldown":1000,"HeightThreshold":5.0,"HighHealth":100,"HighMagic":100,"IgnoredMobs":[],"IgnoredName":"","IsApproachEnabled":false,"IsEngageEnabled":true,"IsHealthEnabled":false,"IsMagicEnabled":false,"LowHealth":50,"LowMagic":50,"MeleeDistance":3.0,"PartyFilter":true,"TargetedMobs":[],"TargetName":"","UnclaimedFilter":false,"WanderDistance":17.0,"Route":{"Waypoints":[],"StraightRoute":true,"Zone":0,"HasWaypoints":false},"HomePointOnDeath":false,"EnableTabTargeting":false,"IsObjectAvoidanceEnabled":false,"FollowDistance":5.0,"FollowedPlayer":"Altalus","StraightRoute":true}`

**Comment by Mercurian** [comment]
I had an instance were 101 stopped working, it seemed like if I changed jobs or logged out, 101 had to be restarted fresh. I would close it, and reopen it (save and load).

Unlike 100 or lower, you could leave it on and start it back up after logging. Could that be your issue?

**Comment by Altalus** [comment]
Well I don't know why but it started working again out of the blue... must be something in my system :)

Sorry for taking your time !

**Comment by Mykezero** [comment]
@Altalus There might be some rare condition in the program that causes it to halt. Would you mind checking to see if the log files contain the error? There should be a logs folder in the directory which contains those files.

**Comment by Altalus** [comment]
Nope, nothing. No stack trace.

 

It was able to detect, say, that I was fighting a mob, and even started doing the JA sepecified in the battle tab, but nothing else. Very weird.

 

______________________________

Guillaume Gingras
