### ISSUE TITLE
Changing melee distance has no effect

### ISSUE THREAD

**Issue by brawndo711** [EasyFarm/EasyFarm#254]
OS: WIN10
Client: Windower and Ashita
EF version: 1.0.109

I've been using the latest release (1.0.109), without any issues. Then today after a reboot (Win10 auto update reboot!), I can no longer adjust melee distance. Also, getting weird behaviors depending is FFXI is focused or not. 

When FFXI is not in focus (on another window), it is putting me at a distance of <1. Sometimes before the mob despawns the melee distance goes to 0, which causes me to spin around the mob. 

Interestingly, if I alt-tab to FFXI, it will push me back some but no more then the closest melee distance (the distance you get without running through them) for a given mob. Although still not the distance I've set in EasyFarm.

Not sure if it matters, but after reboot Windower updated itself. Ashita is exhibiting the same behavior as well. I've tried releases starting at 1.0.98 to the latest, and still can't adjust melee distance. Also tried running as Admin and normal.

**Comment by Mykezero** [comment]
This may have been related to the problems in #255. If you get change, would you mind checking out the new version to see if this is still a problem?
