### ISSUE TITLE
Single position routes goes back and forth around position

### ISSUE THREAD

**Issue by brawndo711** [EasyFarm/EasyFarm#255]
OS: Win10
Client: Windower and Ashita
EF: 1.0.109

Mentioned in Issue #241, currently if I create a route with a single position it will move back and forth around the position. Similar to the behavior described in #253 between characters. It was working last few days with 109, but not sure if recent Win10 or Windower (same happens in Ashita) updates are causing it no longer to work.

**Comment by Mykezero** [comment]
Looks like the new update has broken quite a few things. I'll try to patch this up tonight.

**Comment by Mykezero** [comment]
Somehow I messed up the single waypoint paths again. Thanks for reporting this. I've pushed out a new version which should fix this issue!
