### ISSUE TITLE
Windower Update is causing problems

### ISSUE THREAD

**Issue by Mercurian** [EasyFarm/EasyFarm#257]
I'm only posting this so people know about the issue, don't try to fix it until windower has fully adjusted everything.

If you're 2boxing and using EF, the account that is not "in focus" will not work properly. Sometimes it will not move at all. Sometimes it will randomly run off.

It's a windower update issue, I wouldn't fuck with it until they finish adjustments, but a heads up to those who 2box and use EF on a secondary char.

**Comment by Mykezero** [comment]
Thanks for the heads up! I'll play around with this later tonight.

**Comment by JoshuaTyree** [comment]
https://github.com/Windower/Issues/issues/891

Relevent

**Comment by Crysez** [comment]
just came here to post this as well.  Beat me to it by a whole 2 days!

**Comment by murai78** [comment]
Just tried to use EF today with latest windower hook, and it wont move character if not "in focus".

**Comment by Mercurian** [comment]
Revert back to 4.2 hook (download from ah.com or w/e)

Turn off internet/unplug ethernet

Open windower * characters

Turn on internetafter windower is opened, it will skip the forced update for 4.3

**Comment by andresblanco06** [comment]
Any updates on this issue? Trying to dualbox and it is not working for me at all, I haven't tried the .100 release but I would like to use the latest release. Thanks in advance

**Comment by Altalus** [comment]
Stupid question but did you try with Ashita? I am using it with 2 characters and it seems to work properly.Guillaume Gingras
          
            
            On Jun 25 2017, at 2:23 am, andresblanco06 <notifications@github.com> wrote:
            
            
              Any updates on this issue? Trying to dualbox and it is not working for me at all, I haven't tried the .100 release but I would like to use the latest release. Thanks in advance

**Comment by Mercurian** [comment]
I use 103 and have no issues, the windower team fixed whatever was fucking it up for 2boxers.
