### ISSUE TITLE
Unable to find resources

### ISSUE THREAD

**Issue by lcreed** [EasyFarm/EasyFarm#259]
Trying to auto use skillup pages.  None are being found in resources despite the fact that i can see them in ./resources/items_general.xml
![easyfarmbroken](https://cloud.githubusercontent.com/assets/734957/25758646/3ac79506-3184-11e7-8fc7-afcc925d9c2f.PNG)

**Comment by Mercurian** [comment]
I didn't even know this program worked like that... it fails to find (any?) item for that particular purpose.

Use //pouches windower addon

//pouches Barrels of Fun it will use them until you run out

**Comment by lcreed** [comment]
Good tip to use pouches.  This actually did used to work in easyfarm but not a big deal since there is an option.

**Comment by Mykezero** [comment]
I've upgraded the program to use the most recent Windower resource files. The autocomplete on this should be working now.
