### ISSUE TITLE
Trust Support

### ISSUE THREAD

**Issue by Mykezero** [EasyFarm/EasyFarm#26]
Add support for adventuring fellows and trust companions. Make it so the program waits for the npcs to heal before continuing battle.

**Comment by bugmenot2** [comment]
I want to echo this. I think adding trust support, particularly detecting when your healer trust is at low MP and allowing them time to rest, would greatly improve functionality. Thanks for your continued development, Mykezero, EasyFarm has brought me a lot of happiness.

**Comment by Mykezero** [comment]
Thanks for reminder; I've written it down in my notebook and I'll see what I can do ^^;

**Comment by Mykezero** [comment]
Trust support has been added to EasyFarm. I've create a new issue for the option of resting when your NPCs are injured.
