### ISSUE TITLE
Engage/Route Broken

### ISSUE THREAD

**Issue by ghost** [EasyFarm/EasyFarm#261]
Character just sits there, focuses on target but doesn't engage or run route.

**Comment by Mykezero** [comment]
What area are you farming creatures in? Does this happen in multiple areas or just one?

**Comment by ghost0011** [comment]
Single area in adoulin, basically the character doesn't recognize the path or route, only targets a mob. They broke windower recently with the update and made it go to the PoL screen and says it needs to update, which resets it and makes it reboot, which basically makes your program not run anymore. Only way I found a fix was with ashita but only works sometimes sandboxed. Update just broke the characters engage/run function on windows7, 32bit operating system. Always worked before in any adoulin area until now.

**Comment by Mykezero** [comment]
Yay! Glad it worked out ^^
