### ISSUE TITLE
Can pause be made more responsive?

### ISSUE THREAD

**Issue by rlepidi** [EasyFarm/EasyFarm#262]
It seems the program doesn't do a great job of checking for pause status before doing certain things. Particularly, it appears that once it has chosen a target mob, it will move towards it and engage it even if it's paused. Only once the mob is pulled the program will realize it's in pause status and stop doing anything further.

Could pause checks be added while approaching a target and before pulling it?

**Comment by Mykezero** [comment]
I've added some code that will interrupt the action if the pause operation doesn't complete within half a second. Let me know if this works for you!
