### ISSUE TITLE
Character not in focus 

### ISSUE THREAD

**Issue by Cloudstrafie** [EasyFarm/EasyFarm#263]
Character not in focus will turn and engage but wont move,Any time i click off the game it will stop moveing,If need be i can send a vid to creator showing whats going on

**Comment by nubt** [comment]
Same here, might be related to issue #257

**Comment by Crysez** [comment]
Hey guys,

The solution is in #257.  

Just get the windower 4.2 hook.  Fixed everything.

**Comment by nubt** [comment]
Switching back to version .100 worked for me without fiddling with windower.
