### ISSUE TITLE
Attempts to resummon trusts with agro...then dies

### ISSUE THREAD

**Issue by Crysez** [EasyFarm/EasyFarm#267]
"You cannot use Trust magic while having gained enmity"

Can you add a check so that if the player gets spammed with the above line in their chatlog, then player will stop trying to resummon, kill the mob, then try to resummon trusts again after the mob is dead?

Im having this issue in an agro zone.  I inevitably get killed everynight  when the bot tries to resummon a trust that it released.  This occurs when the bot gets agro'd during the release/resummon cycle.  It tries to spam the trust magic until it ultimately dies.

**Comment by Mykezero** [comment]
Yeah, that definitely doesn't sound good. I'll see what I can do!

**Comment by Gurt89** [comment]
Deleted my post to bump this instead:

![capture](https://user-images.githubusercontent.com/13585196/30411854-687f9b08-98d9-11e7-9ef7-bfea3105fee1.PNG)

After watching this run it seems there just need to be a longer pause between battle end and trust summon. At the top of the screen shot it shows 'Unable to cast a this time'. This is after a new mob is targeted. The trust summon fails, so the program moves forward to combat.

This is the only bug that I'm seeing ATM, so still incredibly impressed :)

**Comment by Mykezero** [comment]
I've finally created a fix for this problem. Please let me know how it works out for you!
