### ISSUE TITLE
Doesn't run while being clicked off game?

### ISSUE THREAD

**Issue by Pulsing** [EasyFarm/EasyFarm#272]
Not sure how to describe this besides the fact of not running while being clicked off the game unless I missed something.

**Comment by hameli2009** [comment]
Yes, I am experiencing the same problem, the bot won't follow the rout recorded unless the game is selected or the tab is on the game, if you unclick to other application it will stand still and fight mobs within the detection distance only.

**Comment by autobot00** [comment]
its windower 4.3.  you need to download the 4.2 exe and hook and block it from updating.  there is a forum post about this on the AH website.  windower 4.3 is seriously whacked out from updating the stuff n junk they updated.  its not the program.

**Comment by Pulsing** [comment]
Could you link the exact post please & thank you?

**Comment by autobot00** [comment]
here is the link
[http://www.ffxiah.com/forum/topic/50802/windower-42-links/](url)

its got a link to download the files.  read through the forum to see how to block windows from updating.  It was a pain in the butt for me to try to get the firewall to work so i did this

add 127.0.0.1	update.windower.net
at the end of c:\windows\system32\drivers\etc\hosts
(you need admin priviledges to edit this file)
This forces an incorrect DNS resolution of the Windower update site.

**Comment by thedraked** [comment]
are you sure about that autobot00?  I have Windower 4.3 on both my desktop and laptop, but for some reason I see this behavior on my desktop but not my laptop.  I will admit that my desktop has a more recent installation of windower, and my laptop was installed initially a while ago.

**Comment by Mykezero** [comment]
This might have been a windower problem.
