### ISSUE TITLE
Easyfarm isn't starting

### ISSUE THREAD

**Issue by TargetAim** [EasyFarm/EasyFarm#274]
I click onto the easy farm program, it asks me if I really want to run the program... I click run it. It looks like it is loading it... Than does nothing. 

I have windows 7, really don't want to change to the up dated version. Other than updating my windows, is there anything that can be done? Thanks

**Comment by Mykezero** [comment]
Hi @TargetAim, Definitely make sure that you are running the program as an administrator. Also, are there any errors in the log file?

Try running the EliteMMO System Checker as well to see if you're missing any of the program's dependencies. 

> If you haven't done so already, try running the EliteMMO System Checker tool to check for any missing packages: 
> * [EliteMMO System Checker](http://www.elitemmonetwork.com/forums/viewtopic.php?f=28&t=329)
> 
> In addition, you'll want to make sure you have .Net 4.5 installed as well, which you can find here: 
> * [Microsoft .Net 4.5](https://www.microsoft.com/en-US/Download/details.aspx?id=30653)
> 
> You'll also want to make sure you are running this program as an administrator by right clicking the EasyFarm.exe file, and selecting Run as Administrator.

**Comment by Mykezero** [comment]
Did any of these suggestions help?
