### ISSUE TITLE
I can't choose the character "easy farm"

### ISSUE THREAD

**Issue by shaduf24** [EasyFarm/EasyFarm#276]
I downloaded the Program, and i start my play online, when i Start the program easy farm, i can't choose the character .

i run ad admin, 
Windows 7
any help please

**Comment by Mykezero** [comment]
Sorry for the late response. Is the program crashing when attempting to select a character? Also, are there any errors in the log folder? 

Hopefully some of these suggestions solves the problem ^^;

> If you haven't done so already, try running the EliteMMO System Checker tool to check for any missing packages: 
> * [EliteMMO System Checker](http://www.elitemmonetwork.com/forums/viewtopic.php?f=28&t=329)
> 
> In addition, you'll want to make sure you have .Net 4.5 installed as well, which you can find here: 
> * [Microsoft .Net 4.5](https://www.microsoft.com/en-US/Download/details.aspx?id=30653)
> 
> You'll also want to make sure you are running this program as an administrator by right clicking the EasyFarm.exe file, and selecting Run as Administrator.
>

**Comment by Mykezero** [comment]
Did any of these suggestions help?
