### ISSUE TITLE
Easy farm still works? 

### ISSUE THREAD

**Issue by mrmankey** [EasyFarm/EasyFarm#281]
I was wondering if easy farm still works for ffxi.  I haven't used this since it was on ffevo at the time.  Just came back to XI just to play around and wondered if this tool is still active.  Thanks

**Comment by Mykezero** [comment]
Yep @mrmankey! Of course since FFACE is no longer maintained, it's now using Atom0s's EliteAPI to power the program. Let me know if you have any problems getting use to the new version ^^
