### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by Gurt89** [EasyFarm/EasyFarm#287]
I'm having this issue when trying to run the build script. See attached. 

![01_build-it](https://user-images.githubusercontent.com/13585196/30040635-940b3ed2-91a7-11e7-915e-430707854bec.PNG)
![02_syscheck](https://user-images.githubusercontent.com/13585196/30040637-97380f40-91a7-11e7-96f9-a93af93a975e.PNG)

I ran a repair for the x86, but they were fine. Would love to help so let me know!

**Comment by Mykezero** [comment]
Hi @Gurt89, Sorry for the confusion! The runnable version of the program can be found here: 
https://github.com/EasyFarm/EasyFarm/releases/download/EasyFarm-1.0.113/EasyFarm.zip

Please let me know if that's what you are looking for ^^

**Comment by Mykezero** [comment]
Also, I'm not sure if there have been any updates for FFXI lately. If you see something strange with the program, don't hesitate to say something!

**Comment by Gurt89** [comment]
Thanks for the link! Unfortunately as soon as I open the program POL crashes. 
![crash](https://user-images.githubusercontent.com/13585196/30117199-1ede12a8-92e5-11e7-923c-424b3d2648fc.PNG)

There have been a few updates to the game

**Comment by Gurt89** [comment]
So I just tried a new few steps. I started the EasyFarm program as admin, and then started Windower. I was able to go all the way to character login. I then added the character to EasyFarm, and then POL crashed.

**Comment by Mykezero** [comment]
If you replace the EliteMMO dll files, the program should work again: 

* http://ext.elitemmonetwork.com/downloads/eliteapi/
* http://ext.elitemmonetwork.com/downloads/elitemmo_api/

Later today, I'll publish a new build that will include these dlls which I think should fix the crashing problem.
