### ISSUE TITLE
How do i start using this tool?

### ISSUE THREAD

**Issue by Aisukage** [EasyFarm/EasyFarm#292]
I have just started playing again after a couple years and use this tool. But i'm not sure where to start anymore i can't even seem to find the exec file to run the program. it may sound really silly but i download the ZIP file and pull out the folder and i just can't seem to find how to start using this anymore at all. No guides anywhere for this so i am wondering if someone can shine a bit of light on the subject for me. Many thanks

**Comment by Sinnersslayer** [comment]
It is wise to look at the githab tabs before posting ;)
https://github.com/EasyFarm/EasyFarm/wiki is just few clicks to the right ;)

**Comment by Mykezero** [comment]
Hi @Aisukage, maybe you downloaded the source files instead of the application?

Here's the link to the newest version of EasyFarm: 
* https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.125

Sorry for taking so long to answer your question.
