### ISSUE TITLE
Item usage support 

### ISSUE THREAD

**Issue by Mykezero** [EasyFarm/EasyFarm#30]
Add support for using items.

**Comment by Mykezero** [comment]
Basic support for this has been added: does not detect if item is in inventory or if it is usable though. 

![image](https://cloud.githubusercontent.com/assets/5349608/13060108/0f81e648-d3fd-11e5-9c02-4ee086503203.png)

**Comment by Sinnersslayer** [comment]
Why it's in End branch?
What with items like Echo Drops which supposed to be used during battles?

**Comment by Mercurian** [comment]
It's just an example. You can put yours in the battle tab.
