### ISSUE TITLE
Won't use any abilities or WS. 

### ISSUE THREAD

**Issue by jbbarrett231** [EasyFarm/EasyFarm#307]
Did a windows 10 update earlier today and ever since I can't get easyfarm to use any abilites or weaponskills. It loads correctly and runs paths, targets mobs, and engages but then only TPs mobs to death. DL'd and repped with most current version (1.0.116) and the issue persists. Please help!

**Comment by jbbarrett231** [comment]
After observing for quite a while I noticed that character was still using Provoke. Tested out adding a WS from under the pull tab, and it successfully worked. So it seems the problem has something to do with the "Battle" tab/section, but doesn't affect the pull tab? Just FYI

**Comment by Mykezero** [comment]
Thanks for the issue @jbbarrett231! This will require a bit of investigation to see what's happening.

**Comment by Mykezero** [comment]
There have been quite a few changes since this ticket. Please try the newest version of EF and see if that fixes the problem: 
* https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.127
