### ISSUE TITLE
How to work it

### ISSUE THREAD

**Issue by darkchylde01** [EasyFarm/EasyFarm#321]
so i have everything opened how how do i actually use easy farm is there a guide somewhere on the site? trying to get my character to auto attack things while im sleep but theres just a bunch of places to type with no guide

**Comment by darkchylde01** [comment]
Ok so it did help however for healing how do I choose to heal a player in party? The only options are self, enemy or unknown

**Comment by AzoRAI** [comment]
You cannot currently set the bot to heal your party.
