### ISSUE TITLE
Cannot berserk, and couple other questions

### ISSUE THREAD

**Issue by PeenX2** [EasyFarm/EasyFarm#325]
Hello there,

Been trying to have EasyFarm do Berserk, but it can't seem to find in repository? Can find Hasso, Innin, and Warcry no problem...but no matter what I try for berserk, like setting what it tells me to do "/jobability Berserk <me>" it will just end up crashing EasyFarm. I tried entering it's index as 15, still nothing. I might have that part confused because I saw the tutorial on how to do this, but it looks like a different version.

Also, trying to have it use Food when it wears off. Also saw another post on how to do this, but can't seem to get it to use Food.

Third thing, which may be impossible. Trying to get it so I stand behind mod. I use August to tank, and I've tried to summon him last so he is sort of far away when I hit and he provokes. But usually doesn't work. Is there a way to get EasyFarm to stand behind mob?

Thanks!!

**Comment by Sinnersslayer** [comment]
I have no issue with Berserk.
Using EasyFarm since v1 and never had a problem with detecting JAs in database.

![izi](https://user-images.githubusercontent.com/33654112/38915299-78dea28c-42e3-11e8-94ca-f124356248de.png)

**Comment by PeenX2** [comment]
Thanks, I figured out berserk. It want's me to select a Macro when creating. So it will say /jobability Berserk <me>.

Too bad there isn't a way to use items when a status changes.

**Comment by Mykezero** [comment]
@zapdosffxi Does this comment help you any?
https://github.com/EasyFarm/EasyFarm/issues/353#issuecomment-395821623

Sorry, I'm not too familiar with aftermath. I'm going to close this ticket, but feel free to comment in ticket #353 if you need more help!
