### ISSUE TITLE
Not an issue, more like a suggestion

### ISSUE THREAD

**Issue by Sinnersslayer** [EasyFarm/EasyFarm#326]
Would be cool if EF would detect when buff wears off and recast it instead of waiting for the Recast timer.
In some situations you loose buff before it's timer runs out.
Blink is one good example when you loose it when mob use AoE magic.
Would be cool if EF would track that kind of buffs and recast it as soon as you loose it.

**Comment by Mercurian** [comment]
It already does that.

**Comment by Sinnersslayer** [comment]
Does recast buffs on fell off?
Where's that topic how to make it use dops?

**Comment by Mercurian** [comment]
There's a box called "on status" that's what you need

**Comment by Sinnersslayer** [comment]
Yeah I'm doing that for Echos and it's still not using it...
Tried it in Tenzen II battle few times.
Ended up using Curer Please just for Sielence removal.

**Comment by Mercurian** [comment]
It (used) to work fine, it seems that there was an update to eliteAPI that may or may not be breaking it currently. I don't use it, and I use an older version. So, I can't say if/why it (currently) doesn't work.

**Comment by Mykezero** [comment]
I've updated the program to use the EliteMMO resource files. Please try the new version to see if echo drop are working now:
* EasyFarm https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.127

Quick tests show that echo drops are usable in this version of the program.
