### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by Murlin6** [EasyFarm/EasyFarm#328]
Whenever I try to open the application, it does not open and just gives a message of An exception has occurred. Could not load file or assembly .... EasyFarm\Release\Ninject.Extensions.Convention.dll or one of its dependencies. Operation is not supported. Cannot figure out how to even open the program.

**Comment by autobot00** [comment]
yeah i havent been able to use the new version either.  I get an error upon trying to open the program.

**Comment by Mykezero** [comment]
That means I screwed up somewhere. I'll see check out what's happening now.

**Comment by Mykezero** [comment]
Actually, would you mind checking the log file? I can't seem to figure it out on this computer.

**Comment by Murlin6** [comment]
[log.txt](https://github.com/EasyFarm/EasyFarm/files/1959371/log.txt)
This one?

**Comment by Mykezero** [comment]
Perfect, that was exactly what I was looking for! I'll see what I can do about getting that patched up.

**Comment by Murlin6** [comment]
Much appreciated ^_^

**Comment by Mykezero** [comment]
Windows might have sandboxed and blocked the file. 

Would you mind try: 

1. Right clicking the Ninject.Extensions.Conventions.dll file,
2. Selecting Properties,
3. And clicking Unblock if it is available?

The properties window should look somewhat like this, except the file name will be different: 

![image](https://user-images.githubusercontent.com/5349608/39412836-22d4ce82-4bf0-11e8-9ee1-e58ecf366779.png)

**Comment by Murlin6** [comment]
I selected unblock but still getting the same error

**Comment by Murlin6** [comment]
I got it! I went through and unblocked all the Ninject files and now it opens ^_^

**Comment by Mykezero** [comment]
Awesome, I'll still need to research to see how I can enable that by default without having people unblock all the files.

**Comment by Murlin6** [comment]
I appreciate the time! Thank you!!

**Comment by Mykezero** [comment]
No problem ^^

**Comment by Mykezero** [comment]
This should be fixed now. I've added a configuration setting which should allow the use of unblocked dlls.
