### ISSUE TITLE
Newest Release: Cannot load file or assembly

### ISSUE THREAD

**Issue by Slened** [EasyFarm/EasyFarm#331]
After extracting the newest release I get this error message when trying to start program. 
 Cannot load file or assembly.......Ninject.Extensions.Conventions.dll or one of its dependencies . Operation is not supported. (Exception from HRESULT:0x80131515)

 Any thoughts ?  Reverting to the older release works just fine.

 Thanks

**Comment by Mykezero** [comment]
Hi @Slened, would you mind trying the steps described in this issue: #328?
You'll need to unblock all of the Ninject dll files to get the newest version working. 

Also, I heard that if you unblock the entire zip folder, then maybe it will extract all files without them being blocked? I haven't tried it, but I heard it might work!

**Comment by Slened** [comment]
I unblocked all of the ninject files and it is now working.

TYVM!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Mykezero** [comment]
Glad it worked ^^
