### ISSUE TITLE
An exception has occured

### ISSUE THREAD

**Issue by Gamingdork** [EasyFarm/EasyFarm#332]
Hello,

First off, thank you for this amazing app and I have been really loving using it.  But I ran into a problem.

About a week ago, after I selected a character I got this message:

Unable to load DLL 'EliteAPI.dll': The Specified module could not be found. (Exception from HRESULT: 0x8007007E).

I have done the "Run As Administrator" for the Windower and Easy Farm, I deleted all of the previous version of Easy Farm and got the latest one with the latest .dll files, I reloaded VC++ 2010-2015 both x86 and x64 and reloaded .NET Framework 4.0,  EliteMMO.SystemCheck comes out green.  I tried the "Unblock" on the EliteAPI.dll that is in the folder.

I am running Windows 7.

Again, thank you for your time for taking care of this project as well as the players.  You are awesome!!

Have a nice day
Grant

**Comment by Mykezero** [comment]
HI, would you mind linking the whole log file? The whole exception might tell us a little more information. Also, do you have antivirus? You might want to try disabling it temporarily to see if it is sandboxing the EliteAPI.dll file.

**Comment by Gamingdork** [comment]
Thank you for your reply.  

I am sorry I don't know how to find the whole log file?  Would you be able to tell me how to do that?

I have disabled my anti-virus and windows defender and the exception still happens.

Thank you again for everything.
Grant

**Comment by Gamingdork** [comment]
Sorry, I think I found it.  Is this correct?

Log Name:      Application
Source:        Application Error
Date:          5/19/2018 11:30:08 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      MonkeyMonster
Description:
Faulting application name: EasyFarm.exe, version: 1.0.110.0, time stamp: 0x590bd087
Faulting module name: KERNELBASE.dll, version: 6.1.7600.17206, time stamp: 0x50e6605e
Exception code: 0xe0434352
Fault offset: 0x0000c41f
Faulting process id: 0x10f8
Faulting application start time: 0x01d3efb88585b63f
Faulting application path: C:\Users\Puppyhead\Desktop\Easyfarm\Release\EasyFarm.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: cd2a5766-5bab-11e8-a590-90fba64a3ebc
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-05-19T21:30:08.000000000Z" />
    <EventRecordID>172052</EventRecordID>
    <Channel>Application</Channel>
    <Computer>MonkeyMonster</Computer>
    <Security />
  </System>
  <EventData>
    <Data>EasyFarm.exe</Data>
    <Data>1.0.110.0</Data>
    <Data>590bd087</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7600.17206</Data>
    <Data>50e6605e</Data>
    <Data>e0434352</Data>
    <Data>0000c41f</Data>
    <Data>10f8</Data>
    <Data>01d3efb88585b63f</Data>
    <Data>C:\Users\Puppyhead\Desktop\Easyfarm\Release\EasyFarm.exe</Data>
    <Data>C:\Windows\syswow64\KERNELBASE.dll</Data>
    <Data>cd2a5766-5bab-11e8-a590-90fba64a3ebc</Data>
  </EventData>
</Event>

**Comment by Mykezero** [comment]
Does the EasyFarm application load up at all or is the window never shown? Looking at the event view information you've linked, it suggests that the program doesn't start up at all. 

If you haven't done so already, try to install .NET 4.5 as well: 
* https://www.microsoft.com/en-US/Download/details.aspx?id=30653

Also, the log files I was talking would have been contained in EF/Logs folder like in this picture: 

![image](https://user-images.githubusercontent.com/5349608/40280995-6e0e4aec-5c29-11e8-8779-995f17abfdb8.png)

**Comment by Gamingdork** [comment]
Hi,

Sorry.  Yes, it dos start up but when I select a character, the message occurs and Easyfarm crashes.

I just updated and repaired .NET 4.5 

[easyfarm.0.log](https://github.com/EasyFarm/EasyFarm/files/2021012/easyfarm.0.log)
[easyfarm.1.log](https://github.com/EasyFarm/EasyFarm/files/2021013/easyfarm.1.log)
[easyfarm.2.log](https://github.com/EasyFarm/EasyFarm/files/2021014/easyfarm.2.log)
[easyfarm.3.log](https://github.com/EasyFarm/EasyFarm/files/2021015/easyfarm.3.log)
[easyfarm.log](https://github.com/EasyFarm/EasyFarm/files/2021016/easyfarm.log)

Thank you again
Grant

**Comment by Mykezero** [comment]
I might have to debug this on a fresh Windows 7 installation to see what is happening. I'll try to work through this tonight to see what dependencies are needed on a fresh system: there must be something I'm missing. 

Would you mind trying to unblock the whole zip file before extracting the files? That will unblock every dll in the folder. I doubt it's a blocked dll problem though.

**Comment by Mykezero** [comment]
I was able to replicate the problem on Windows 7! I'll start trying to debug this now to see what exactly is needed to get this running.

**Comment by Mykezero** [comment]
Hi, I was able to get it working on Windows 7. Try installing these dependencies and let me know if they work!

* [VC++ 2008(x86)](https://www.microsoft.com/en-us/download/details.aspx?id=5582)
* [VC++ 2010 (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=8328)
* [VC++ 2012 (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=30679)
* [VC++ 2015 (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=48145)
* [.NET Framework 4.7](https://www.microsoft.com/net/download/dotnet-framework-runtime/net47)

I've added the screen shot here showing what's installed on the Amazon Workspace Windows 7 desktop. 

![image](https://user-images.githubusercontent.com/5349608/40462657-e18b3ed2-5ede-11e8-8f05-bc5a462975f7.png)

**Comment by Gamingdork** [comment]
Thank you so much for your time and effort.  I really appreciate this!  

You are so awesome!  I will load what you sent and let you know what happens.

Have a nice day
Grant

**Comment by Gamingdork** [comment]
Good morning,

Sorry I have not replied sooner.

I am still working on the problem.  Apparently, I don't have the Windows 7 Service Pack 1 installed.  After I installed it, I have been having other problems with Windower now.  But once I get those fixed, I will let you know.
Thank you again for all that you do.

Have a great weekend
Grant

**Comment by Gamingdork** [comment]
Thank you!  That did the trick!  

You are awesome!!
Have a great weekend!

**Comment by Mykezero** [comment]
No problem, glad it's working now! ^^
