### ISSUE TITLE
Can not find 'abils' value

### ISSUE THREAD

**Issue by Sinnersslayer** [EasyFarm/EasyFarm#345]
I have upgraded to the new version .124 and when I try to run it, it show me this error.
It's in polish but says something about being not able to find 'abils' value.

https://puu.sh/AvMJB/5d31fbf088.png

**Comment by Mykezero** [comment]
Actually, do you have a copy of the log file as well?
It will have a file name like log.txt or log.#####.txt. 
The log will tell me what piece of code had a problem.

**Comment by Mykezero** [comment]
I'll install the Polish language pack and will debug through this problem.

**Comment by Sinnersslayer** [comment]
[log.txt](https://github.com/EasyFarm/EasyFarm/files/2066355/log.txt)

There you go.
Sorry was on vacations w/o internet access ;)

**Comment by Mykezero** [comment]
Awesome, thanks for the log file!

**Comment by Sinnersslayer** [comment]
Still having same issue with latest release .126

**Comment by Mykezero** [comment]
New version of the program uses EliteMMO resources, and no longer uses Windower resources:
https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.127

This removes the piece of code that was acting up entirely. Let me know if this helps!

**Comment by Sinnersslayer** [comment]
Yeah, the error is gone.
Thanks Myke :)

**Comment by Mykezero** [comment]
@Sinnersslayer Thanks for the update, and glad it's working now ^^
