### ISSUE TITLE
new start/pause button is good stuff how about the others?

### ISSUE THREAD

**Issue by autobot00** [EasyFarm/EasyFarm#346]
just wanted to say the new start/pause is a sweet little addition.

How about buttons for select character, load/save?  can do away with the drop downs and just make way for buttons.  everybody likes buttons.

and nice work on the program.

**Comment by Mykezero** [comment]
Hi @khoa002, Would you like to make buttons for these commands as well, like you did for the start button in PR #342?

Optionally, we can also move the remaining Window menu items (AlwaysOnTop and Minimize To System Tray) into the Title Bar: 
* https://stackoverflow.com/a/23180880

**Comment by khoa002** [comment]
@Mykezero Sure, no problem. I'll make the additions and send over a PR when it's ready.

**Comment by khoa002** [comment]
@Mykezero Please review https://github.com/EasyFarm/EasyFarm/pull/351

**Comment by Mykezero** [comment]
Awesome, I'll take a look at the new changes later tonight.

**Comment by Mykezero** [comment]
The new buttons are available in the latest release: 
* https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.124

This definitely makes using those options less of a chore!

Thanks again for the help @khoa002 ^^
