### ISSUE TITLE
Setting up Pull Action with Ranged weapon

### ISSUE THREAD

**Issue by Oldfeathers** [EasyFarm/EasyFarm#347]
Hi, I've been trying to follow the wiki to set up a Pull action using a ranged weapon, however when I click "Auto-Fill" I get the message "Auto-Fill failed to find Ranged in resources."

Am I missing a file or did the method to set up ranged pulls change?

**Comment by Mykezero** [comment]
Ok, this should be fixed in the newest version of EasyFarm now. 
* https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.125

**Comment by Oldfeathers** [comment]
Thanks man, I really love that you've made this for us.

**Comment by Hdelamatta** [comment]
HELLO mykezero. I'm new to easyfarm, I have used it to lever up my samurai which I got the code for the sam job but I'm trying to make new ones for other job and I can't make them to work. Could I get some other jobs like healing or pet jobs, ranger, ninja etc  or a link where to get them? I researched everything and I can't find the eup codes anywhere.
