### ISSUE TITLE
EasyFarm doesn't seem to work with Windower

### ISSUE THREAD

**Issue by ChronoTrigger01** [EasyFarm/EasyFarm#355]
So finally started to use windower again but it seems that when i start easyfarm up it just targets a mob and stares at it and does nothing. Ashita on the other hand works perfectly fine. Maybe its something with windower? Or is there some fix for this through easyfarm?

**Comment by danmansyx9** [comment]
Works with my Windower. Have you installed latest version of easy farm? And also you have to open easyfarm first before launching Windower. Took me a while to figure that out when I first started.

**Comment by ChronoTrigger01** [comment]
Got latest version, but haven't tried before launch. Ill give that a go and hit yah back thx for response^^

**Comment by ChronoTrigger01** [comment]
Nope, didnt work for me :( and removed all addon/plug ins aswell to see if maybe windower was causing it.

**Comment by danmansyx9** [comment]
Stupid question but do you have Approach enabled? I tend to overlook the simplest stuff lol

**Comment by ChronoTrigger01** [comment]
Yep everything good as far as settings go for it lol

**Comment by Barrbar** [comment]
I'm having the same issue as ChronoTrigger01. I checked my settings and everything is set correctly. EasyFarm stares at the mob without approaching or engaging. When I manually initiate a fight weapon skills that I've set will not fire.

**Comment by Mykezero** [comment]
I develop the program using the Windower client, so it should support it. Does the program work without creating any actions?

**Comment by Barrbar** [comment]
I tried running EF without actions and I got the same result. Do i have to add files to the EF folder manually? I've used EF in the past and I'm just starting to use it again so maybe I missed something?

**Comment by palookaville** [comment]
Having same issue as OP using latest build through windower. Just came back after long absence and used to use it all the time. Not sure if this helps, but here is log.txt extract:


2018-06-18 19:08:16.1627 EasyFarm.Logging.NLogTextFileLogger FSM thread interrupted
System.Threading.ThreadInterruptedException: Thread was interrupted from a waiting state.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at MemoryAPI.Memory.EliteMmoWrapper.NavigationTools.MoveForwardTowardsPosition(Func`1 targetPosition, Boolean useObjectAvoidance) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 124
   at MemoryAPI.Memory.EliteMmoWrapper.NavigationTools.GotoWaypoint(Position position, Boolean useObjectAvoidance, Boolean keepRunning) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 91
   at EasyFarm.States.TravelState.Run() in C:\projects\easyfarm\EasyFarm\States\TravelState.cs:line 67
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 156
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 98

**Comment by palookaville** [comment]
Not sure if this helps or not, but everything is loaded to my E: drive, not C.
That includes ffxi, windower, EF.
Thanks.

**Comment by ChronoTrigger01** [comment]
Still doesnt work for me tried reseting PC and what not and nothing, Just stares at mob and follows it with the camera in first person view lol

**Comment by ChronoTrigger01** [comment]
I use on Ashita just fine, could maybe ashita in stalled affect windower?

**Comment by R3P0FFXI** [comment]
I just reformatted my laptop on Windows 10 1809 and am using Easyfarm 1.0.26 I can confirm this problem as well with the latest windower version. Easyfarm takes the game into first person mode and then just sits there.

I have 2 items checked engage and approach under the battle settings. I am on the latest eliteapi.dll that wanted to download when i first ran easyfarm.  I did not add any additional claim settings or engage settings. 

I did make sure to choose the process and I am running both Windower and Easyfarm as admin.

**Comment by R3P0FFXI** [comment]
@Mykezero the fix for this is simple the new version of windower no longer has an installer and the keyboard_allowmmf 1 was removed from the init.txt file as soon as I added that back in easyfarm works

**Comment by ChronoTrigger01** [comment]
The init.txt would be the settings file? mine looks like this. Where would i need to place that line?
<?xml version="1.0" encoding="UTF-8"?>
-<settings>
-<autoload>
<addon>autojoin</addon>
<addon>BLUAlert</addon>
<addon>bluguide</addon>
<addon>boxdestroyer</addon>
<addon>distance</addon>
<addon>DistancePlus</addon>
<addon>enemybar</addon>
<addon>enternity</addon>
<addon>FastCS</addon>
<addon>giltracker</addon>
<addon>GearSwap</addon>
<addon>findAll</addon>
<addon>InfoBar</addon>
<addon>invtracker</addon>
<addon>JobChange</addon>
<addon>latentchecker</addon>
<addon>Logger</addon>
<addon>lottery</addon>
<addon>MyHome</addon>
<addon>ohShi</addon>
<addon>Omen</addon>
<addon>organizer</addon>
<addon>PetTP</addon>
<addon>plugin_manager</addon>
<addon>pointwatch</addon>
<addon>Pouches</addon>
<addon>RAWR</addon>
<addon>roe</addon>
<addon>rolltracker</addon>
<addon>salvage2</addon>
<addon>SATACast</addon>
<addon>scoreboard</addon>
<addon>send</addon>
<addon>SpellCheck</addon>
<addon>targetinfo</addon>
<addon>TParty</addon>
<plugin>Guildwork</plugin>
<plugin>InfoBar</plugin>
</autoload>
-<profile name="">
<consolekey>Insert</consolekey>
<windowmode>Window</windowmode>
<width>1920</width>
<height>1080</height>
<uiscale>1</uiscale>
<alwaysenablegamepad>false</alwaysenablegamepad>
</profile>
</settings>

**Comment by ChronoTrigger01** [comment]
Where would i place that line in the windower settings?

**Comment by ChronoTrigger01** [comment]
I dont see any init.txt in my windower files

**Comment by ChronoTrigger01** [comment]
[Sample.txt](https://github.com/EasyFarm/EasyFarm/files/2113160/Sample.txt)
This is what i have as far as settings go that i saw i assume this the init file? If so where would i place that line @R3P0FFXI

**Comment by R3P0FFXI** [comment]
its under the scripts folder place that line at the very top of the file, you may need to create the file as I did in the windower/scripts dir as the new installer gets rid of the file completly

**Comment by ChronoTrigger01** [comment]
Would you be able to send me a copy of yours?

**Comment by Barrbar** [comment]
I dropped an init.txt from a random 'master' windower folders here on GitHub. EF works perfectly now thank you!

**Comment by ChronoTrigger01** [comment]
Can you link me that folder @Barrbar

**Comment by Barrbar** [comment]
https://github.com/Feary/Windower4

**Comment by ChronoTrigger01** [comment]
Omg thank you!!! worked finally

**Comment by zmann408** [comment]
I don't see a scripts folder in windower folder

**Comment by palookaville** [comment]
Brilliant!
I knew it would be something simple I was missing.
Thanks heaps for all the responses.
@zmann408 the scripts folder you are pointing at needs it added

**Comment by zmann408** [comment]
@palookaville how do I copy that text file? to put into the folder?

**Comment by palookaville** [comment]
I just copied all the text of the init.txt file from inside github and created a new text file in scripts, named it init.txt and pasted all the text in and saved it.

**Comment by Clandestine350** [comment]
I placed an init.txt into the scripts folder that included just the line

keyboard_allowmmf 1

And i doesn't want to load. I keep getting the error "Could not execute1 init.txt - File was not found. - 2"

What am I doing wrong?
