### ISSUE TITLE
Enhancement: Is it possible to setup the shortcut to auto-load a specified profile?

### ISSUE THREAD

**Issue by Brandario** [EasyFarm/EasyFarm#361]
So I multi-box using EasyFarm and don't like to have to load up each profile everytime I'm ready to play. Just wondering if its possible or easy to make the shortcut automatically load up a specific profile.

Thanks.

**Comment by Mykezero** [comment]
Yep, I'm hoping that the last session for a character can be automatically loaded after character selection. Afterwards, you would optionally have the option to load a settings file through the menu.

**Comment by Mykezero** [comment]
Pushed new version of EasyFarm that will load the settings for a previously selected character. 
* https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.128

Please check this out and let me know if this was what you were looking for ^^
