### ISSUE TITLE
Trouble re-summoning AAEV

### ISSUE THREAD

**Issue by Shijin-kun** [EasyFarm/EasyFarm#363]
Ive noticed that if you set the bot to summon AAEV it will summon it when its not out but if you set the bot to re-summon her when her mp or hp gets to a certain point it does not re-summon her. I have no basis on this but i think it might be that her spell name is AAEV but her name in the party list is ArkEV.

**Comment by Mykezero** [comment]
We might need to add some extra code to handle this situation.

**Comment by ckmorris** [comment]
This issue should be resolved by pull request #383.

**Comment by Mykezero** [comment]
The pull request has been merged in and the new changes are available in the latest release:  
[EasyFarm 1.0.132](https://github.com/EasyFarm/EasyFarm/releases/tag/EasyFarm-1.0.132)
