### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Ledicious** [EasyFarm/EasyFarm#385]
Can anyone help me out?  I have Visual Studio installed and have tried to build this multiple times but it keeps failing with multiple errors.  Unfortunately, I'm not a developer and do not understand the build process completely.  The build instruction seem a bit vague to me, but obviously its just me.  Can anyone give me a "hand holding" guide to building and making this run?

**Comment by ifattah** [comment]
You don't need to download the source if you're familiar. You can simple click Releases and download the latest version, in executable form.

**Comment by Mykezero** [comment]
Yep. No need to download and compile from source: 
https://github.com/EasyFarm/EasyFarm/releases
