### ISSUE TITLE
SCH Ability.

### ISSUE THREAD

**Issue by Yuchemey** [EasyFarm/EasyFarm#412]
I have been trying to Figure out how SCH, Accession/Perpetuance could work. But i have found a way to cast Accession/Regen V but it seems that when i try to add Perpetuance to the mix... Easy Farm is trying to reactivate the same ability over and over.

**Comment by AzoRAI** [comment]
EF currently doesn't handle ability "chains", at best you could get lucky with execution order to make it work.
