### ISSUE TITLE
Setting uploads

### ISSUE THREAD

**Issue by jediarmy** [EasyFarm/EasyFarm#413]
Can anyone upload setting for level 1-50 mobs for exp?
So the only thing I need to do is add mobs in the bot.

**Comment by Yagamyi** [comment]
It requires multiple zones, so your best bet is to just set it up yourselve.   
Their are xp guides on bg wiki, that show camps.  

Using the navigation is easy, for ja's , spells, etc enter name then use the auto fill button to get them to work.

**Comment by AzoRAI** [comment]
There's currently no way to target multiple zones with one profile, you'll need to set up multiple profiles for level ranges.
