### ISSUE TITLE
EasyFarm not detecting Character 

### ISSUE THREAD

**Issue by Flowertje** [EasyFarm/EasyFarm#420]
I know it was fixed before with a new EliteAPI, atm im wondering if im the only one with this issue since it worked fine for me up untill last week or so. Sorry ^_^

**Comment by AzoRAI** [comment]
Have you tried using an older version of the program? Made sure your DLLs are trusted?

**Comment by Flowertje** [comment]
Tried older version, doesnt work. It randomly started working again and after literally changing nothing, it stopped working again. Select character comes up with a bunch of stuff but not ffxi. This happens when im single boxing, multiboxing you name it...  yes i run everything as admin. all files are trusted. no clue whats going on
