### ISSUE TITLE
Not using trusts sometimes.

### ISSUE THREAD

**Issue by Mcluv** [EasyFarm/EasyFarm#428]
1. When i first log into the game it wont use trusts sometimes, it will just stand there till i manually call 1 trust then it starts working every time. It always does this on all my accounts.
2. If the Trust dies or i have to re summon it for MP it will keep trying to call trust even if i have agro till i eventually Die, idk if this was fixed in last release. Seems to be working now or i cant get it to happen.
3. Now after i did the recent windows update it will sometimes run into battle with out calling trusts. The only way i found to make it work is to agro the mobs standing at the start of my waypoint then pos warp to the hp to de pop them then pos warp back to get it to work lol.
It didnt used to do this and pretty sure its only happening at 1 camp, idk if the recent updates would effect it but started happening as soon as i did one of these, not sure which one
![Capture](https://user-images.githubusercontent.com/31917130/54248768-17e6ea00-44fb-11e9-8cfb-07b16f84d1e5.PNG)

**Comment by jeffsanford** [comment]
seems like it calls 0 1 2 or any number of trusts sometimes, idk why maybe has something to do with running to long, it starts to call them really slow if running to long, re start the app, it sometimes calls all 5 trusts properly and calls them fast, idk maybe need more ram or something, i am running 8 at a time with 32 gb ram

**Comment by jeffsanford** [comment]
sorry for all the issues, but also cant re summon King of Hearts at any mp range
