### ISSUE TITLE
Jerking foward to backward

### ISSUE THREAD

**Issue by Barrsy** [EasyFarm/EasyFarm#440]
A friend who also uses this experiences this same problem but just deals with it. I've looked long and hard to find a solution and tried multiple things to no avail.

I record a route, in first person, as smoothly as I can.

Once I hit start, every 10-15 seconds my guy will start spasming forward / backward before continuing on the route. I've adjusted my distance settings, rerecorded the route, etc.

Help.

**Comment by MatthewJHBerry** [comment]
How'd you fix it lol

**Comment by Barrsy** [comment]
for me, to fix the jerking, i had to turn off another software that was running along with XI and easyfarm at the same time, once i just ran only easyfarm and XI the jerking stopped.

**Comment by MatthewJHBerry** [comment]
Thanks!
