### ISSUE TITLE
Select character fails

### ISSUE THREAD

**Issue by kafuin** [EasyFarm/EasyFarm#486]
As of the 11/10/20 update easyfarm no longer connects to a character with the select character button, therefore the entire program does not work.

**Comment by queenhawk** [comment]
Confirmed, broken after version update. Using Windower.

**Comment by FarisBeitar** [comment]
Yes, How can we contact the developer to fix this please? :(
Or else ffxi will suck my time with farming merits and CP..

**Comment by raboley** [comment]
Same using Ashita.

I think it is actually a problem with EliteMMOWrapper. Debugging the selection process you get nothing from line 57 of SelectCharacter.cs

```c#
// SelectCharacter.cs
            // Get memory reader set in config file.
            MemoryWrapper fface = MemoryWrapper.Create(process.Id);
```

I will see if this still works in a private server.

**Comment by NyoX01** [comment]
Glad and Sad it's not only me that's having problems.
Pls Dev, bless us with the option of using this masterpiece again.

**Comment by Hypelios** [comment]
Same, I am also having this issue.  Checked for any new EliteMMO.API.dll and EliteAPI.DLL updates but still nothing.

**Comment by Chacbolay** [comment]
The same API theme was in Cure Please and it's already resolved let's wait and have an easy update

**Comment by ria-leberu** [comment]
Elitemmo discord has an updated beta version of Eliteapi in response to the November 2020 update. I've replaced the file in my EasyFarm folder, and it works now.

**Comment by Hypelios** [comment]
@raboley Thanks for the hint.. this has fixed my issue as well.

**Comment by ChrisWilko1990** [comment]
i downloaded the new API and still nothing ?

**Comment by WolfeMasters** [comment]
I'm not sure how to update this, anyone have a walkthrough?

**Comment by queenhawk** [comment]
> I'm not sure how to update this, anyone have a walkthrough?

Wherever you have EasyFarm located, you take the new .dll file and paste it there, allowing it to overwrite the existing one.

**Comment by NyoX01** [comment]
Anyone ever have a problem with EF going to a new mob before the first mob is dead, or not re-summoning trusts when their mp is low, or having it lock on to a mob and just follow it?

**Comment by edavis317** [comment]
@NyoX01  I am having this sort of issue - ive had to make sure tab targeting is checked but every so often it will disengage from the current target to engage another. Additionally it does not approach properly at times and will just sit there.
