### ISSUE TITLE
Targeting is weird

### ISSUE THREAD

**Issue by edavis317** [EasyFarm/EasyFarm#489]
After the recent update I had to reinstall EasyFarm - on both pc's not sure why. The biggest issue I am facing now is that I have to have "use tab targeting" active in order to engage enemies. Originally I had this off and really had no issues.

What happens when this is off is the target name will appear and disappear rapidly and he will just stand there.

Any thoughts?

**Comment by DrakeFS** [comment]
The recent update required an update to the EliteAPI.dll (which EasyFarm uses).  I have seen\had no issues with the targeting since updating the dll file myself.

**Comment by joshuateveryday** [comment]
Seems to not be any issues with target at this time. Closing.
