### ISSUE TITLE
Remote server returned an error (522) on startup

### ISSUE THREAD

**Issue by Monosss** [EasyFarm/EasyFarm#512]
Starting up the app causes this error. It's only started recently.

![Easy Farm error](https://user-images.githubusercontent.com/14229267/156820133-adb32705-fb77-4228-9b4d-aee2c67692dd.JPG)

**Comment by ValerieValidus** [comment]
I am having the same issue, just started today for me

**Comment by Monosss** [comment]
Looks like the server is back up now.
