### ISSUE TITLE
Well shit. Newest update broke it again.

### ISSUE THREAD

**Issue by Mercurian** [EasyFarm/EasyFarm#532]
Fantastic. They changed the hook system again. Shits broken. Sad day.

**Comment by Darwinion** [comment]
It broke yesterday over 12 hours before the latest update. I was getting error code 522 as were others.

**Comment by Mercurian** [comment]
I know that now. If you were running it before yesterday and didn't close it, it continued to work. There was no way I could've known at the time.

**Comment by Mercurian** [comment]
Was connected to the site outtage and not the update
