### ISSUE TITLE
Magic halts execution

### ISSUE THREAD

**Issue by kkychuck** [EasyFarm/EasyFarm#533]
Everything was working fine up until this morning when I reloaded my game for the first time since the update.  Now any process that uses either black magic, white magic, or blue magic just stops working.  the instance does not crash it just stops executing any new steps and does not output anything new to the log. last log entry is "Now Targeting ...."

strangely bard songs do not seem to be affected by this.

**Comment by kkychuck** [comment]
seems only some spells cause this issue.....

**Comment by Bwool40** [comment]
I am having the same issue, it kept stopping.  I saw this thread, clicked off all my spells and now its working fine.

**Comment by DrakeFS** [comment]
Make sure the EMMO dlls are the latest.  Remaking the setup from scratch can also fix the issue.
